import {NextRequest,NextResponse} from 'next/server';
import {principalFor} from '@/lib/workspace-auth/session';
import {sameOrigin,inputBody,privateHeaders} from '@/lib/workspace-auth/http';
import {activeSources} from '@/lib/booking-sources/config';
import {RedisWorkspaceStore} from '@/lib/workspace-auth/store';
import {canUseFinance,readFinance,applyFinance,writeFinance,calendarIncome} from '@/lib/finance-store';
async function scope(request:NextRequest,property:unknown,year:unknown){const actor=await principalFor(request);if(!actor)throw new Error('UNAUTHORIZED');if(!canUseFinance(actor))throw new Error('FORBIDDEN');const properties=activeSources().filter(s=>actor.allProperties||actor.propertyIds.includes(s.property.id)).map(s=>({id:s.property.id,name:s.property.name}));const id=typeof property==='string'&&property?property:properties[0]?.id;if(!id||!properties.some(p=>p.id===id))throw new Error('FORBIDDEN');const parsed=Number(year);if(!Number.isInteger(parsed)||parsed<2020||parsed>2100)throw new Error('INVALID_INPUT');return {actor,properties,property:id,year:parsed};}
function failure(e:unknown){const code=e instanceof Error?e.message:'';const errors:Record<string,[number,string]>={UNAUTHORIZED:[401,'請先登入。'],FORBIDDEN:[403,'財務僅開放此旅宿的擁有者、God 與 Admin。'],INVALID_INPUT:[400,'請確認日期、金額、分類及說明。'],FUTURE_DATE:[400,'這裡記錄已發生收支，日期不能晚於今天。'],VERSION_CONFLICT:[409,'帳本已更新，請重新載入後確認。'],IDEMPOTENCY_CONFLICT:[409,'原請求內容不同，請重新載入。'],WRITE_UNCONFIRMED:[503,'儲存結果尚未確認，請保留原內容重試。'],RATE_LIMITED:[429,'操作較頻繁，請稍後重試。']};const [status,detail]=errors[code]??[503,'財務資料暫時無法完整讀取，請稍後重試。'];return NextResponse.json({code:errors[code]?code:'UNAVAILABLE',detail},{status,headers:privateHeaders});}
export async function GET(request:NextRequest){try{const ctx=await scope(request,request.nextUrl.searchParams.get('property'),request.nextUrl.searchParams.get('year'));const [{state},income]=await Promise.all([readFinance(ctx.property,ctx.year),calendarIncome(ctx.property,ctx.year)]);return NextResponse.json({properties:ctx.properties,property_id:ctx.property,year:ctx.year,version:state.version,entries:[...state.entries,...income].sort((a,b)=>b.date.localeCompare(a.date)||b.created_at.localeCompare(a.created_at)),updated_at:new Date().toISOString()},{headers:privateHeaders});}catch(e){return failure(e);}}
export async function POST(request:NextRequest){try{sameOrigin(request);const input=await inputBody(request);const ctx=await scope(request,input.property_id,input.year);await new RedisWorkspaceStore().limit(`finance:${ctx.actor.id}`,90,3600);const {raw,state}=await readFinance(ctx.property,ctx.year);const result=applyFinance(state,input,ctx.actor,ctx.property,ctx.year);if(result.state!==state)await writeFinance(ctx.property,ctx.year,raw,result.state,String(input.request_id));return NextResponse.json({verified:true,entry_id:result.entry_id,version:result.state.version},{headers:privateHeaders});}catch(e){return failure(e);}}
