import {NextRequest,NextResponse} from 'next/server';
import {principalFor} from '@/lib/workspace-auth/session';
import {sameOrigin,inputBody,privateHeaders} from '@/lib/workspace-auth/http';
import {activeSources} from '@/lib/booking-sources/config';
import {randomUUID} from 'node:crypto';
import {readOperationalSheet} from '@/lib/sheet-monitor/google';
import {normalizeRows,HEADERS} from '@/lib/sheet-monitor/reconcile';
import {adaptSheetBookings} from '@/lib/booking-sources/sweetfun-sheet';
import {checkRows} from '@/lib/os-payments';
import {financeContext} from '@/lib/finance-context';
import {validateFinanceLinks} from '@/lib/finance-projection';
import {RedisWorkspaceStore,redisCommand} from '@/lib/workspace-auth/store';
import {canUseFinance,applyFinance,writeFinance} from '@/lib/finance-store';
async function scope(request:NextRequest,property:unknown,year:unknown){const actor=await principalFor(request);if(!actor)throw new Error('UNAUTHORIZED');if(!canUseFinance(actor))throw new Error('FORBIDDEN');const properties=activeSources().filter(s=>actor.allProperties||actor.propertyIds.includes(s.property.id)).map(s=>({id:s.property.id,name:s.property.name}));const id=typeof property==='string'&&property?property:properties[0]?.id;if(!id||!properties.some(p=>p.id===id))throw new Error('FORBIDDEN');const parsed=Number(year);if(!Number.isInteger(parsed)||parsed<2020||parsed>2100)throw new Error('INVALID_INPUT');return {actor,properties,property:id,year:parsed};}
function failure(e:unknown){const code=e instanceof Error?e.message:'';const errors:Record<string,[number,string]>={UNAUTHORIZED:[401,'請先登入。'],FORBIDDEN:[403,'財務僅開放此旅宿的擁有者、God 與 Admin。'],SOURCE_CONFLICT:[409,'來源訂單有衝突，請先到日曆核對。'],NOT_FOUND:[409,'訂單已變動或不存在，請重新整理後核對。'],ORDER_REQUIRED:[400,'住宿收入請選擇對應訂單，才能同步扣抵應收。'],INVALID_INPUT:[400,'請確認日期、金額與分類。'],FUTURE_DATE:[400,'這裡記錄已發生收支，日期不能晚於今天。'],VERSION_CONFLICT:[409,'帳本已更新，請關閉此視窗、重新整理後再確認。'],IDEMPOTENCY_CONFLICT:[409,'原請求內容不同，請重新載入。'],WRITE_UNCONFIRMED:[503,'儲存結果尚未確認，請保留原內容重試。'],RATE_LIMITED:[429,'操作較頻繁，請稍後重試。']};const [status,detail]=errors[code]??[503,'財務資料暫時無法完整讀取，請稍後重試。'];return NextResponse.json({code:errors[code]?code:'UNAVAILABLE',detail},{status,headers:privateHeaders});}
export async function GET(request:NextRequest){try{const ctx=await scope(request,request.nextUrl.searchParams.get('property'),request.nextUrl.searchParams.get('year'));const report=await financeContext(activeSources().find(s=>s.property.id===ctx.property)!,ctx.year);return NextResponse.json({properties:ctx.properties,property_id:ctx.property,year:ctx.year,version:report.state.version,versions:report.versions,entries:report.entries.sort((a,b)=>b.date.localeCompare(a.date)||b.created_at.localeCompare(a.created_at)),orders:report.orders,recurring:report.recurring,due:report.due,payout_rules:report.payout_rules,excluded_orders:report.excluded_orders,projection_version:report.projection_version,updated_at:new Date().toISOString()},{headers:privateHeaders});}catch(e){return failure(e);}}
export async function POST(request:NextRequest){let lock:{key:string;token:string}|null=null;try{sameOrigin(request);const input=await inputBody(request);const ctx=await scope(request,input.property_id,input.year);await new RedisWorkspaceStore().limit(`finance:${ctx.actor.id}`,90,3600);
 const key=`sweetfun-os:payments:v1:${ctx.property}:lock`,token=randomUUID();if(await redisCommand(['SET',key,token,'NX','EX',60])!=='OK')throw new Error('VERSION_CONFLICT');lock={key,token};
 const report=await financeContext(activeSources().find(s=>s.property.id===ctx.property)!,ctx.year);
 const replay=report.state.operations.some(o=>o.id===input.request_id);
 if(!replay){if(input.projection_version!==report.projection_version)throw new Error('VERSION_CONFLICT');validateFinanceLinks(input,report.orders,report.entries,report.recurring,ctx.year,report.asof);if(Array.isArray(input.allocations)&&input.allocations.length){const source=activeSources().find(s=>s.property.id===ctx.property)!;const normalized=normalizeRows(await readOperationalSheet(source),source);const live=adaptSheetBookings([HEADERS,...normalized.map(r=>r.cells)],source.sourceId,new Date().toISOString(),[],normalized.map(r=>r.sourceRow),source.property);for(const a of input.allocations){if(checkRows(live.bookings,ctx.property,a.order_id).source_version!==report.orders.find(o=>o.id===a.order_id)?.source_version)throw new Error('VERSION_CONFLICT');}}}
 const result=applyFinance(report.state,input,ctx.actor,ctx.property,ctx.year);if(result.state!==report.state)await writeFinance(ctx.property,ctx.year,report.raw,result.state,String(input.request_id),lock);
 return NextResponse.json({verified:true,entry_id:result.entry_id,version:result.state.version},{headers:privateHeaders});}catch(e){return failure(e);}finally{if(lock)await redisCommand(['EVAL',"if redis.call('GET',KEYS[1])==ARGV[1] then return redis.call('DEL',KEYS[1]) end return 0",1,lock.key,lock.token]).catch(()=>{});}}
