"use client";
import {useIntlLocale} from "@/components/i18n/language-provider";
import {useT} from "@/components/i18n/language-provider";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {ExpenseCategorySelect} from './expense-category-select';
import {PLATFORMS,EXPENSE_CATEGORIES,METHODS,revenueSummary,taipeiDate,type FinanceReport,type FinanceOrder,type DueExpense} from '@/lib/finance-model';
import {useFinanceSave} from './use-finance-save';
const money=(v:number,locale="zh-TW")=>new Intl.NumberFormat(locale,{style:'currency',currency:'TWD',maximumFractionDigits:2}).format(v/100);
const input='mt-1 block w-full rounded-lg border bg-white p-2.5 text-sm';
const box='min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm';
export function RevenueCharts({report,month}:{report:FinanceReport;month:string}){
const uiLocale = useIntlLocale();

  const uiText = useT();

 const [hover,setHover]=useState('');
 const values=Array.from({length:12},(_,i)=>({month:i+1,...revenueSummary(report.orders,report.entries,`${month.slice(0,4)}-${String(i+1).padStart(2,'0')}`)}));
 const max=Math.max(1,...values.map(v=>v.total));const s=revenueSummary(report.orders,report.entries,month);
 const tooltip=(v:typeof s,label:string)=>`${label} · ${uiText("已收")} ${money(v.received, uiLocale)} / ${uiText("應收")} ${money(v.receivable, uiLocale)} / ${uiText("本月總收入")} ${money(v.total, uiLocale)}`;
 return <section className={box}><h2 className="font-semibold">{month.slice(0,4)} {uiText("年訂房收入")}</h2><p className="mt-1 text-xs text-slate-500">{uiText("按入住月份，已收與應收以目前紀錄拆分；其他服務收入按收款月份。總收入不代表已入帳。")}</p><div className="mt-5 grid gap-6 lg:grid-cols-[2fr_1fr]"><div><div className="flex h-40 items-end gap-2 border-b">{values.map(v=><button key={v.month} aria-label={tooltip(v,`${v.month} ${uiText("月")}`)} title={tooltip(v,`${v.month} ${uiText("月")}`)} onMouseEnter={()=>setHover(tooltip(v,`${v.month} ${uiText("月")}`))} onFocus={()=>setHover(tooltip(v,`${v.month} ${uiText("月")}`))} onClick={()=>setHover(tooltip(v,`${v.month} ${uiText("月")}`))} className="flex h-full min-w-0 flex-1 flex-col justify-end"><span className="w-full rounded-t bg-amber-300" style={{height:`${v.receivable/max*100}%`}}/><span className="w-full bg-teal-700" style={{height:`${Math.max(v.total?0:1,v.received/max*100)}%`}}/></button>)}</div><div className="mt-2 flex gap-2 text-center text-xs text-slate-500">{values.map(v=><span className="flex-1" key={v.month}>{v.month}</span>)}</div><p className="mt-3 min-h-10 text-xs text-slate-600" role="status">{uiText(hover||'滑過長條或點選月份查看金額。')}</p></div><InteractiveDonut items={[{label:'已收',amount:s.received,color:'#0f766e'},{label:'應收',amount:s.receivable,color:'#fcd34d'}]} label={uiText("本月總收入")}/></div></section>;
}
export function InteractiveDonut({items,label}:{items:{label:string;amount:number;color:string}[];label:string}){
const uiLocale = useIntlLocale();

  const uiText = useT();

 const [active,setActive]=useState<number|null>(null);const total=items.reduce((s,c)=>s+c.amount,0);
 const current=active===null?null:items[active];
 return <div className="flex flex-wrap items-center justify-center gap-4"><div className="relative size-40 shrink-0"><svg viewBox="0 0 100 100" className="size-full -rotate-90" aria-label={uiText(label)}><circle cx="50" cy="50" r="38" fill="none" stroke="#f1f5f9" strokeWidth="17"/>{items.map((c,i)=>{const length=total?c.amount/total*100:0;const start=total?items.slice(0,i).reduce((s,v)=>s+v.amount,0)/total*100:0;return length>0?<circle key={uiText(c.label)} cx="50" cy="50" r="38" pathLength="100" fill="none" stroke={c.color} strokeWidth={active===i?20:17} strokeDasharray={`${length} ${100-length}`} strokeDashoffset={-start} tabIndex={0} role="button" aria-label={`${uiText(c.label)} ${money(c.amount, uiLocale)}，${Math.round(length)}%`} onMouseEnter={()=>setActive(i)} onMouseLeave={()=>setActive(null)} onFocus={()=>setActive(i)} onBlur={()=>setActive(null)} onClick={()=>setActive(i)}><title>{uiText(c.label)}：{money(c.amount, uiLocale)}（{Math.round(length)}%）</title></circle>:null;})}</svg><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-xs text-slate-500">{uiText(current?.label??label)}</span><strong className="mt-1 text-sm">{money(current?.amount??total, uiLocale)}</strong></div></div><div className="min-w-36 flex-1 space-y-2">{items.filter(c=>c.amount>0).map(c=><p key={uiText(c.label)} className="flex items-center gap-2 text-xs"><span className="size-2 rounded-full" style={{background:c.color}}/><span className="flex-1">{uiText(c.label)}</span><span>{money(c.amount, uiLocale)} · {Math.round(c.amount/total*100)}%</span></p>)}{!total&&<p className="text-xs text-slate-400">{uiText("尚無紀錄")}</p>}</div></div>;
}
export function Receivables({report,month,onReceive,onRules}:{report:FinanceReport;month:string;onReceive:(order?:FinanceOrder)=>void;onRules:()=>void}){
const uiLocale = useIntlLocale();

  const uiText = useT();

 const [platform,setPlatform]=useState('all'),[all,setAll]=useState(false);
 const orders=report.orders.filter(o=>o.receivable>0&&(all||o.check_in.startsWith(month))&&(platform==='all'||o.platform===platform));
 return <section className={box}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">{uiText("應收帳款")}</h2><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={onRules}>{uiText("平台入帳規則")}</Button><Button onClick={()=>onReceive()}>{uiText("登記收到房費")}</Button></div></div><div className="my-4 flex flex-wrap gap-3 text-sm"><select aria-label={uiText("應收平台")} className="rounded-lg border bg-white p-2" value={platform} onChange={e=>setPlatform(e.target.value)}><option value="all">{uiText("全部平台")}</option>{Object.entries(PLATFORMS).map(([k,v])=><option value={k} key={k}>{uiText(v)}</option>)}</select><label className="flex items-center gap-2"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>{uiText("跨月份未收款（含過去與未來）")}</label></div><p className="mb-3 text-xs text-slate-500">{orders.length} {uiText("筆 · 應收")}{money(orders.reduce((s,o)=>s+o.receivable,0), uiLocale)}{uiText("。Agoda 退房 30 天後可請款；提出 claim 後尚未入帳，仍列應收。")}</p><div className="max-h-[28rem] divide-y overflow-y-auto">{orders.map(o=><div key={o.id} className="flex flex-wrap items-center gap-3 py-3 text-sm"><div className="min-w-0 flex-1"><p className="font-medium">{uiText(PLATFORMS[o.platform]??o.platform)} · {o.rooms.join('、')}</p><p className="text-xs text-slate-500">{o.check_in.replaceAll('-','/')}–{o.check_out.replaceAll('-','/')}</p>{o.eligible_date&&<p className="mt-1 text-xs text-amber-800">{o.platform==='agoda'?uiText("可請款日"):uiText("預計入帳日")} {o.eligible_date.replaceAll('-','/')} · {o.eligible_date<=taipeiDate()?uiText("已到期"):uiText("未到期")}</p>}{o.source_paid&&<p className="text-xs text-slate-500">{uiText("來源表：客人已付清，旅宿入帳待登記")}</p>}</div><div className="text-right"><p>{uiText("應收")}{money(o.receivable, uiLocale)}</p><p className="text-xs text-teal-700">{uiText("已收")}{money(o.received, uiLocale)}</p></div><Button size="sm" variant="outline" onClick={()=>onReceive(o)}>{uiText("登記入帳")}</Button></div>)}</div>{!orders.length&&<p className="py-6 text-center text-sm text-slate-500">{uiText("此範圍沒有應收款。")}</p>}{report.orders.some(o=>o.credit>0)&&<p role="status" className="mt-3 text-xs text-amber-800">{uiText("有")}{report.orders.filter(o=>o.credit>0).length} {uiText("筆訂單的實收超過目前來源房費，可能曾改單，請核對明細；差額不自動當成其他收入。")}</p>}{report.excluded_orders>0&&<p role="status" className="mt-3 text-xs text-amber-800">{uiText("另有")}{report.excluded_orders} {uiText("組來源資料待核對，未計入應收；請在日曆核對。")}</p>}</section>;
}
export function RecurringPanel({report,month,onNew,onPay,onChanged}:{report:FinanceReport;month:string;onNew:()=>void;onPay:(due:DueExpense)=>void;onChanged:()=>void}){
const uiLocale = useIntlLocale();

  const uiText = useT();

 const [stop,setStop]=useState<string|null>(null);const {save,busy,error,pending}=useFinanceSave(report,()=>{setStop(null);onChanged();});
 const due=report.due.filter(d=>d.date<=month+'-31');
 return <section className={box}><div className="flex items-center justify-between gap-2"><h2 className="font-semibold">{uiText("循環支出 · 待付款")}{due.length} {uiText("筆")}</h2><Button variant="outline" onClick={onNew}>{uiText("設定循環支出")}</Button></div><p className="mt-2 text-xs text-slate-500">{uiText("每月到期自動列出，確認付款後才列入支出。31 日遇短月份會改為月底；包含之前未付項目。")}</p>{due.map(d=><div key={d.id} className="flex items-center gap-3 border-b py-3 text-sm"><div className="flex-1"><p>{d.description||uiText(d.category_name??EXPENSE_CATEGORIES[d.category as keyof typeof EXPENSE_CATEGORIES])}</p><p className="text-xs text-slate-500">{uiText("到期")}{d.date.replaceAll('-','/')}</p></div><span>{money(d.amount_cents, uiLocale)}</span><Button size="sm" variant="outline" onClick={()=>onPay(d)}>{uiText("確認付款")}</Button></div>)}<details className="mt-4 text-sm"><summary className="cursor-pointer">{uiText("循環設定（")}{report.recurring.length}）</summary>{report.recurring.map(r=><div className="flex items-center gap-3 py-3" key={r.id}><span className="flex-1">{r.description||uiText(r.category_name??EXPENSE_CATEGORIES[r.category as keyof typeof EXPENSE_CATEGORIES])} {uiText("· 每月")}{r.day} {uiText("日 ·")}{money(r.amount_cents, uiLocale)}{r.stopped_at?uiText(" · 已停止"):''}</span>{!r.stopped_at&&<Button size="sm" variant="outline" onClick={()=>setStop(r.id)}>{uiText("停止循環")}</Button>}</div>)}</details><Dialog open={!!stop} onOpenChange={o=>!o&&!busy&&!pending&&setStop(null)}><DialogContent showCloseButton={!busy&&!pending}><DialogTitle>{uiText("停止循環支出")}</DialogTitle><DialogDescription>{uiText("停止明天起的新項目；已到期與已付款紀錄會保留。")}</DialogDescription>{error&&<p role="alert">{uiText(error)}</p>}<Button disabled={busy} onClick={()=>{const rule=report.recurring.find(r=>r.id===stop);if(rule)void save({action:'recurring_stop',rule_id:stop,year:rule.year});}}>{uiText("確認停止")}</Button></DialogContent></Dialog></section>;
}
export function RecurringForm({report,onClose,onSaved}:{report:FinanceReport;onClose:()=>void;onSaved:()=>void}){
  const [categoryName,setCategoryName]=useState('');
 const uiText = useT();

 const [category,setCategory]=useState('internet'),[amount,setAmount]=useState(''),[description,setDescription]=useState(''),[start,setStart]=useState(taipeiDate()),[end,setEnd]=useState(''),[day,setDay]=useState('10'),[method,setMethod]=useState('bank_transfer');const {save,busy,error,pending}=useFinanceSave(report,onSaved);
 return <Dialog open onOpenChange={o=>!o&&!busy&&!pending&&onClose()}><DialogContent showCloseButton={!busy&&!pending} className="max-h-[90dvh] overflow-y-auto"><DialogTitle>{uiText("設定循環支出")}</DialogTitle><DialogDescription>{uiText("每月產生待付款項目，不會自動扣款或記成已付。")}</DialogDescription><form className="space-y-4" onSubmit={e=>{e.preventDefault();void save({action:'recurring_create',category,...(category==='custom'||category.startsWith('custom_')?{category_name:category==='custom'?categoryName:report.expense_categories?.[category]}:{}),amount:Number(amount),description,start,end:end||null,day:Number(day),method,year:Number(start.slice(0,4))});}}><fieldset disabled={busy||!!pending} className="space-y-3"><ExpenseCategorySelect categories={report.expense_categories} value={category} onChange={setCategory} name={categoryName} onName={setCategoryName}/><label className="block text-sm">{uiText("每月金額")}<input className={input} required type="number" min="0.01" max="10000000" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="block text-sm">{uiText("說明（選填）")}<input className={input} maxLength={500} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="grid grid-cols-2 gap-3"><label className="min-w-0 text-sm">{uiText("開始日期")}<input className={input} required type="date" min="2020-01-01" max="2099-12-31" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="min-w-0 text-sm">{uiText("結束日期（選填）")}<input className={input} type="date" min={start} max="2099-12-31" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label className="block text-sm">{uiText("每月幾日到期")}<input className={input} required type="number" min="1" max="31" value={day} onChange={e=>setDay(e.target.value)}/></label><label className="block text-sm">{uiText("預設付款方式")}<select className={input} value={method} onChange={e=>setMethod(e.target.value)}>{Object.entries(METHODS).filter(([k])=>k!=='ota').map(([k,v])=><option key={k} value={k}>{uiText(v)}</option>)}</select></label></fieldset>{error&&<p role="alert" className="text-sm text-red-700">{uiText(error)}</p>}<Button disabled={busy} type="submit">{busy?uiText("儲存中…"):pending?uiText("重試原設定"):uiText("儲存循環設定")}</Button></form></DialogContent></Dialog>;
}
export function PayoutRulesForm({report,onClose,onSaved}:{report:FinanceReport;onClose:()=>void;onSaved:()=>void}){
  const uiText = useT();

 const [platform,setPlatform]=useState('ctrip'),[mode,setMode]=useState(report.payout_rules.find(r=>r.platform==='ctrip')?.mode??'manual'),[day,setDay]=useState(String(report.payout_rules.find(r=>r.platform==='ctrip')?.day??10)),[offset,setOffset]=useState(String(report.payout_rules.find(r=>r.platform==='ctrip')?.offset??1));const {save,busy,error,pending}=useFinanceSave(report,onSaved);
 return <Dialog open onOpenChange={o=>!o&&!busy&&!pending&&onClose()}><DialogContent showCloseButton={!busy&&!pending}><DialogTitle>{uiText("平台入帳規則")}</DialogTitle><DialogDescription>{uiText("預計日期用來提醒；實際收到匯款後，再登記入帳。")}</DialogDescription><form className="space-y-4" onSubmit={e=>{e.preventDefault();void save({action:'payout_rule',platform,mode,day:Number(day),offset:Number(offset)});}}><fieldset disabled={busy||!!pending} className="space-y-3"><label className="block text-sm">{uiText("平台")}<select className={input} value={platform} onChange={e=>{const p=e.target.value,r=report.payout_rules.find(r=>r.platform===p);setPlatform(p);setMode(r?.mode??'manual');setDay(String(r?.day??10));setOffset(String(r?.offset??1));}}><option value="ctrip">Trip.com</option><option value="owljourney">{uiText("奧丁丁")}</option></select></label><label className="block text-sm">{uiText("模式")}<select className={input} value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="manual">{uiText("平台匯款後手動登記")}</option><option value="monthly">{uiText("設定每月預計入帳日")}</option></select></label>{mode==='monthly'&&<><label className="block text-sm">{uiText("退房月份之後")}<select className={input} value={offset} onChange={e=>setOffset(e.target.value)}><option value="1">{uiText("次月")}</option><option value="2">{uiText("第 2 個月")}</option><option value="3">{uiText("第 3 個月")}</option></select></label><label className="block text-sm">{uiText("每月幾日")}<input className={input} required min="1" max="31" type="number" value={day} onChange={e=>setDay(e.target.value)}/></label></>}</fieldset><p className="text-xs text-slate-500">{uiText("Agoda 固定顯示退房後 30 天可請款；可累積後再一次登記多筆訂單入帳。")}</p>{error&&<p role="alert" className="text-red-700">{uiText(error)}</p>}<Button disabled={busy} type="submit">{pending?uiText("重試原設定"):uiText("儲存設定")}</Button></form></DialogContent></Dialog>;
}
