"use client";
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,Plus,ChevronLeft,ChevronRight,RefreshCw,Receipt,Wallet,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {EXPENSE_CATEGORIES,INCOME_CATEGORIES,METHODS,categoryLabel,summarize,type FinanceEntry,type FinanceKind,type FinanceReport} from '@/lib/finance-model';
const money=(cents:number)=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:cents%100?2:0}).format(cents/100);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const stageLabel:Record<string,string>={deposit:'訂金',balance:'尾款',full:'全額',other:'其他款項'};
const COLORS=['#264653','#2a9d8f','#80b6a4','#d7ad58','#c67e59','#7d83a5','#a3aab5','#80926d','#b69b86','#d2d6d9'];
const expenseColor=(id:string)=>COLORS[Math.max(0,Object.keys(EXPENSE_CATEGORIES).indexOf(id))%COLORS.length];
const box='rounded-2xl border border-slate-200 bg-white p-5 shadow-sm';
const inputClass='mt-1.5 block w-full min-w-0 rounded-lg border bg-white px-3 py-2.5 text-sm';
export function FinanceWorkspace({view}:{view:'overview'|'bookkeeping'}){
 const router=useRouter(),query=useSearchParams();
 const rawMonth=query.get('month')??today().slice(0,7);
 const month=/^(20\d{2})-(0[1-9]|1[0-2])$/.test(rawMonth)?rawMonth:today().slice(0,7);
 const property=query.get('property')??'';
 const [reload,setReload]=useState(0);
 const requestKey=`${month}:${property}:${reload}`;
 const [result,setResult]=useState<{key:string;data:FinanceReport|null;error:string}|null>(null);
 const loading=result?.key!==requestKey;
 const data=loading?null:result?.data??null;
 const error=loading?'':result?.error??'';
 const [kind,setKind]=useState<FinanceKind>('expense'),[search,setSearch]=useState(''),[category,setCategory]=useState('all');
 const [formKind,setFormKind]=useState<FinanceKind|null>(null),[voidEntry,setVoidEntry]=useState<FinanceEntry|null>(null),[detail,setDetail]=useState<FinanceEntry|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch(`/api/v1/finance?year=${month.slice(0,4)}&property=${encodeURIComponent(property)}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const response=await r.json();if(!r.ok)throw new Error(response.detail);if(!controller.signal.aborted)setResult({key:requestKey,data:response,error:''});}).catch(e=>{if(!controller.signal.aborted)setResult({key:requestKey,data:null,error:e.message});});return()=>controller.abort();},[month,property,requestKey]);
 const summary=useMemo(()=>summarize(data?.entries??[],month),[data,month]);
 const monthly=(data?.entries??[]).filter(e=>e.date.startsWith(month));
 const filtered=monthly.filter(e=>e.kind===kind&&(category==='all'||e.category===category)&&`${e.description} ${categoryLabel(e)} ${e.actor}`.toLowerCase().includes(search.toLowerCase()));
 function navigate(nextMonth=month,nextProperty=property,target=view){router.push(`/finance${target==='bookkeeping'?'/bookkeeping':''}?month=${nextMonth}&property=${encodeURIComponent(nextProperty||data?.property_id||'')}`);}
 function shift(n:number){const date=new Date(month+'-01T00:00:00Z');date.setUTCMonth(date.getUTCMonth()+n);navigate(date.toISOString().slice(0,7));}
 const changed=()=>{setReload(v=>v+1);setNotice('已儲存並確認。');};
 return <div className="mx-auto max-w-7xl space-y-6 pb-8 text-slate-800">
  <header className="flex flex-wrap items-end justify-between gap-4 pt-2"><div><p className="text-xs font-semibold tracking-[.16em] text-teal-700">FINANCE · 財務</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">{view==='overview'?'把每一筆收支，看得清楚。':'記帳'}</h1><p className="mt-2 text-sm text-slate-500">{view==='overview'?'從日常記帳，掌握旅宿的花費與收款。':'按實際收付款日期整理，每一筆都有來源與紀錄。'}</p></div><Button disabled={!data||loading} onClick={()=>setFormKind('expense')} className="h-11 bg-teal-800 px-5 text-white hover:bg-teal-900"><Plus className="size-4"/>新增支出</Button></header>
  <div className="flex flex-wrap items-center justify-between gap-3 border-b pb-3"><nav className="flex gap-5 text-sm font-medium" aria-label="財務功能"><Link className={view==='overview'?'text-teal-800 underline underline-offset-8':'text-slate-500'} href={`/finance?month=${month}&property=${property}`}>財務首頁</Link><Link className={view==='bookkeeping'?'text-teal-800 underline underline-offset-8':'text-slate-500'} href={`/finance/bookkeeping?month=${month}&property=${property}`}>記帳</Link></nav><div className="flex flex-wrap items-center gap-2"><select aria-label="選擇記帳旅宿" value={data?.property_id??property} disabled={!data} onChange={e=>navigate(month,e.target.value)} className="max-w-44 rounded-lg border bg-white p-2 text-sm">{data?.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="flex items-center rounded-lg border bg-white"><Button size="icon" variant="ghost" aria-label="上一個月" disabled={month<='2020-01'} onClick={()=>shift(-1)}><ChevronLeft className="size-4"/></Button><input aria-label="記帳月份" type="month" min="2020-01" max="2099-12" value={month} onChange={e=>e.target.value&&navigate(e.target.value)} className="w-32 bg-transparent text-sm"/><Button size="icon" variant="ghost" aria-label="下一個月" disabled={month>='2099-12'} onClick={()=>shift(1)}><ChevronRight className="size-4"/></Button></div><Button size="icon" variant="ghost" aria-label="重新整理財務" onClick={()=>setReload(v=>v+1)}><RefreshCw className={`size-4 ${loading?'animate-spin':''}`}/></Button></div></div>
  {notice&&<p role="status" className="text-sm text-teal-800">{notice}</p>}
  {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error} <Button variant="outline" size="sm" onClick={()=>setReload(v=>v+1)}>重試</Button></div>}
  {loading&&<div className={`${box} py-16 text-center text-slate-500`}>正在核對帳本與日曆收款…</div>}
  {data&&!loading&&<>
   <div className="grid gap-3 sm:grid-cols-3">{[{label:'本月已登記收入',value:summary.income,icon:ArrowDownLeft,color:'text-teal-800',hint:'含日曆收款與手動收入'},{label:'本月已登記支出',value:summary.expense,icon:ArrowUpRight,color:'text-slate-800',hint:`${monthly.filter(e=>e.kind==='expense'&&e.status==='active').length} 筆支出紀錄`},{label:'本月收支差額',value:summary.net,icon:Wallet,color:summary.net<0?'text-amber-800':'text-slate-800',hint:'已登記收入 − 已登記支出，非會計淨利'}].map(m=><div key={m.label} className={box}><div className="flex justify-between text-sm text-slate-500">{m.label}<m.icon className="size-4"/></div><p className={`mt-3 text-3xl font-semibold tabular-nums tracking-tight ${m.color}`}>{money(m.value)}</p><p className="mt-2 text-xs text-slate-500">{m.hint}</p></div>)}</div>
   <p className="text-xs leading-5 text-slate-500">以實際收付款日期統計；未登記不代表沒有發生。日曆付款自動帶入，不重複記帳。{summary.ota>0&&<> 本月含 OTA 代收 {money(summary.ota)}，尚未核對撥款，不代表旅宿銀行入帳。</>}</p>
   <div className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><ExpenseTrend values={summary.monthly} year={month.slice(0,4)} selected={Number(month.slice(5))}/><ExpenseDonut categories={summary.categories} total={summary.expense}/></div>
   {view==='overview'?<section className={box}><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">本月最近收支</h2><button className="flex items-center gap-1 text-sm text-teal-800" onClick={()=>navigate(month,property,'bookkeeping')}>查看記帳 <ArrowRight className="size-4"/></button></div>{monthly.length?<EntryList entries={monthly.slice(0,6)} onSelect={setDetail}/>:<Empty onAdd={()=>setFormKind('expense')}/>}</section>:<section className={box}>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-lg bg-slate-100 p-1" role="group" aria-label="收支分類">{(['expense','income'] as FinanceKind[]).map(k=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setCategory('all');}} className={`rounded-md px-5 py-2 text-sm font-semibold ${kind===k?'bg-white shadow-sm':'text-slate-500'}`}>{k==='expense'?'支出':'收入'}</button>)}</div>{kind==='income'&&<Button variant="outline" onClick={()=>setFormKind('income')}><Plus className="size-4"/>新增收入</Button>}</div>
    {kind==='income'&&<p className="mt-3 text-xs leading-5 text-slate-500">收入按服務分類；訂金、尾款、全額是收款階段。已在日曆登記的款項會自動列入。日曆的「其他款項」先歸其他收入。</p>}
    <div className="my-4 flex flex-wrap gap-2"><input aria-label="搜尋記帳" placeholder="搜尋說明、分類或登記人" value={search} onChange={e=>setSearch(e.target.value)} className="min-w-0 flex-1 rounded-lg border p-2.5 text-sm"/><select aria-label="篩選記帳分類" value={category} onChange={e=>setCategory(e.target.value)} className="max-w-40 rounded-lg border bg-white p-2 text-sm"><option value="all">全部分類</option>{Object.entries(kind==='expense'?EXPENSE_CATEGORIES:INCOME_CATEGORIES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>
    {filtered.length?<EntryList entries={filtered} onSelect={setDetail}/>:<Empty onAdd={()=>setFormKind(kind)} filtered={!!search||category!=='all'} kind={kind}/>}
   </section>}
   <p className="text-right text-xs text-slate-400">更新於 {new Date(data.updated_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false})} · TWD 新台幣</p>
  </>}
  {data&&formKind&&<EntryForm kind={formKind} report={data} month={month} onClose={()=>setFormKind(null)} onSaved={()=>{setFormKind(null);changed();}}/>}
  <Dialog open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><DialogContent className="max-h-[85dvh] overflow-y-auto"><DialogTitle>記帳明細</DialogTitle><DialogDescription>查看這筆收支的來源與登記紀錄。</DialogDescription>{detail&&<div className="space-y-3 text-sm"><p className="text-3xl font-semibold">{money(detail.amount_cents)}</p><p>{detail.date.replaceAll('-','/')} · {categoryLabel(detail)} · {METHODS[detail.method]}</p><p className="whitespace-pre-wrap break-words">{detail.description}</p><p>來源：{detail.source==='calendar'?'日曆付款自動帶入':'手動記帳'}{detail.stage?` · ${stageLabel[detail.stage]??''}`:''}</p><p>登記人：{detail.actor}</p><p className="text-xs text-slate-500">登記時間：{new Date(detail.created_at).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',hour12:false})}</p>{detail.status==='void'?<p className="rounded-lg bg-amber-50 p-3">已作廢：{detail.void_reason} · {detail.void_actor}</p>:detail.source==='manual'?<Button variant="outline" onClick={()=>{setVoidEntry(detail);setDetail(null);}}>作廢這筆紀錄</Button>:<p className="text-xs text-slate-500">這筆來自日曆付款，財務頁不會重複新增或覆寫。</p>}</div>}</DialogContent></Dialog>
  {data&&voidEntry&&<VoidForm report={data} entry={voidEntry} onClose={()=>setVoidEntry(null)} onSaved={()=>{setVoidEntry(null);changed();}}/>}
 </div>;
}
function EntryList({entries,onSelect}:{entries:FinanceEntry[];onSelect:(entry:FinanceEntry)=>void}){return <div className="divide-y">{entries.map(e=><button key={e.id} onClick={()=>onSelect(e)} className="flex w-full items-center gap-3 py-3.5 text-left hover:bg-slate-50"><span className={`flex size-9 shrink-0 items-center justify-center rounded-xl ${e.kind==='income'?'bg-teal-50 text-teal-700':'bg-slate-100 text-slate-500'}`}>{e.kind==='income'?<ArrowDownLeft className="size-4"/>:<ArrowUpRight className="size-4"/>}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{e.description}</span><span className="mt-1 block text-xs text-slate-500">{e.date.slice(5).replace('-','/')} · {categoryLabel(e)}{e.source==='calendar'?' · 日曆收款':''}{e.stage?` · ${stageLabel[e.stage]}`:''}{e.status==='void'?' · 已作廢':''}</span></span><span className={`shrink-0 text-sm font-semibold tabular-nums ${e.status==='void'?'text-slate-400 line-through':e.kind==='income'?'text-teal-800':'text-slate-800'}`}>{e.kind==='income'?'+':'−'}{money(e.amount_cents)}</span></button>)}</div>;}
function Empty({onAdd,filtered=false,kind='expense'}:{onAdd:()=>void;filtered?:boolean;kind?:FinanceKind}){return <div className="py-12 text-center"><Receipt className="mx-auto mb-3 size-8 text-slate-300"/><p className="font-medium">{filtered?'沒有符合條件的紀錄':'這個月還沒有記帳資料'}</p><p className="mt-2 text-sm text-slate-500">{filtered?'試著換一個分類或搜尋文字。':'新增第一筆，開始累積清楚的收支紀錄。'}</p>{!filtered&&<Button variant="outline" className="mt-5" onClick={onAdd}><Plus className="size-4"/>新增{kind==='expense'?'支出':'收入'}</Button>}</div>;}
function ExpenseTrend({values,year,selected}:{values:{month:number;expense:number}[];year:string;selected:number}){const max=Math.max(...values.map(v=>v.expense),100);return <section className={box}><h2 className="font-semibold">{year} 年支出趨勢</h2><p className="mt-1 text-xs text-slate-500">依支出發生月份 · 全年已登記 {money(values.reduce((s,v)=>s+v.expense,0))}</p><div className="relative mt-6"><div className="flex h-44 items-end gap-2 border-b border-slate-200 px-1" role="img" aria-label={values.map(v=>`${v.month}月 ${money(v.expense)}`).join('、')}>{values.map(v=><div className="flex h-full min-w-0 flex-1 items-end" key={v.month}><div title={`${v.month}月：${money(v.expense)}`} className={`w-full rounded-t-md ${v.month===selected?'bg-teal-800':'bg-teal-200'}`} style={{height:v.expense?`${Math.max(2,v.expense/max*100)}%`:'2px'}}/></div>)}</div><div className="mt-2 flex gap-2 px-1 text-center text-[10px] text-slate-500">{values.map(v=><span className="min-w-0 flex-1" key={v.month}>{v.month}月</span>)}</div></div>{values.every(v=>!v.expense)&&<p className="mt-4 text-xs text-slate-400">尚無支出紀錄；新增後會呈現每月趨勢。</p>}<details className="mt-4 text-xs text-slate-500"><summary className="cursor-pointer">查看每月金額</summary><div className="mt-2 grid grid-cols-3 gap-2">{values.map(v=><span key={v.month}>{v.month}月 {money(v.expense)}</span>)}</div></details></section>;}
function ExpenseDonut({categories,total}:{categories:{id:string;label:string;amount:number}[];total:number}){let angle=0;const stops=categories.map(c=>{const start=angle;angle+=c.amount/total*360;return `${expenseColor(c.id)} ${start}deg ${angle}deg`;});return <section className={box}><h2 className="font-semibold">本月支出分布</h2><p className="mt-1 text-xs text-slate-500">看看花費集中在哪些項目</p><div className="mt-5 flex flex-wrap items-center justify-center gap-6"><div role="img" aria-label={total?categories.map(c=>`${c.label} ${money(c.amount)}`).join('、'):'本月尚無支出'} className="flex size-40 shrink-0 items-center justify-center rounded-full" style={{background:total?`conic-gradient(${stops.join(',')})`:'#f1f5f9'}}><div className="flex size-28 flex-col items-center justify-center rounded-full bg-white"><span className="text-[10px] text-slate-500">本月支出</span><strong className="mt-1 text-lg tabular-nums">{money(total)}</strong></div></div><div className="min-w-36 flex-1 space-y-2.5">{categories.length?categories.map(c=><div key={c.id} className="flex items-center gap-2 text-xs"><span className="size-2 shrink-0 rounded-full" style={{background:expenseColor(c.id)}}/><span className="flex-1">{c.label}</span><span className="tabular-nums">{money(c.amount)}</span><span className="w-9 text-right text-slate-400">{Math.round(c.amount/total*100)}%</span></div>):<p className="text-sm text-slate-400">新增支出後，<br/>這裡會顯示分類占比。</p>}</div></div></section>;}
function useFinanceSave(report:FinanceReport,onSaved:()=>void){const [busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<Record<string,unknown>|null>(null);async function save(fields:Record<string,unknown>){setBusy(true);setError('');const payload=pending??{...fields,property_id:report.property_id,year:report.year,expected_version:report.version,request_id:crypto.randomUUID()};setPending(payload);try{const r=await fetch('/api/v1/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await r.json();if(!r.ok){if(r.status<500)setPending(null);throw new Error(result.detail);}if(!result.verified)throw new Error('結果尚未確認，請保留原內容重試。');setPending(null);onSaved();}catch(e){setError(e instanceof Error?e.message:'連線中斷，請重試原紀錄。');}finally{setBusy(false);}}return {busy,error,pending,save};}
function EntryForm({kind,report,month,onClose,onSaved}:{kind:FinanceKind;report:FinanceReport;month:string;onClose:()=>void;onSaved:()=>void}){
 const [category,setCategory]=useState(kind==='expense'?'laundry':'lodging'),[amount,setAmount]=useState(''),[date,setDate]=useState(month===today().slice(0,7)?today():month+'-01'),[description,setDescription]=useState(''),[method,setMethod]=useState('bank_transfer'),[stage,setStage]=useState('');
 const {busy,error,pending,save}=useFinanceSave(report,onSaved);
 return <Dialog open onOpenChange={open=>!open&&!busy&&!pending&&onClose()}><DialogContent showCloseButton={!busy&&!pending} className="max-h-[90dvh] overflow-y-auto"><DialogTitle>新增{kind==='expense'?'支出':'收入'}</DialogTitle><DialogDescription>{report.properties.find(p=>p.id===report.property_id)?.name} · 依實際收付款日期記錄</DialogDescription><form onSubmit={e=>{e.preventDefault();void save({action:'create',kind,category,amount:Number(amount),date,description,method,stage});}} className="space-y-4">
 <fieldset disabled={busy||!!pending} className="grid min-w-0 gap-4 disabled:opacity-60"><div className="grid min-w-0 grid-cols-2 gap-3"><label className="min-w-0 text-sm">金額（元）<input autoFocus required type="number" min="0.01" max="10000000" step="0.01" placeholder="0" value={amount} onChange={e=>setAmount(e.target.value)} className={inputClass}/></label><label className="min-w-0 text-sm">{kind==='expense'?'付款':'收款'}日期<input required type="date" min={`${report.year}-01-01`} max={today()<`${report.year}-12-31`?today():`${report.year}-12-31`} value={date} onChange={e=>setDate(e.target.value)} className={inputClass}/></label></div>
 <label className="text-sm">分類<select value={category} onChange={e=>setCategory(e.target.value)} className={inputClass}>{Object.entries(kind==='expense'?EXPENSE_CATEGORIES:INCOME_CATEGORIES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label className="text-sm">{kind==='expense'?'支出說明':'收入說明'}<input required maxLength={500} placeholder={kind==='expense'?'例如：9 月床單送洗':'例如：早餐加購 2 份'} value={description} onChange={e=>setDescription(e.target.value)} className={inputClass}/></label>
 <label className="text-sm">付款方式<select value={method} onChange={e=>setMethod(e.target.value)} className={inputClass}>{Object.entries(METHODS).filter(([key])=>kind==='income'||key!=='ota').map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 {kind==='income'&&category==='lodging'&&<label className="text-sm">收款階段<select value={stage} onChange={e=>setStage(e.target.value)} className={inputClass}><option value="">未指定</option>{Object.entries(stageLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}
 {kind==='income'&&<p className="rounded-lg bg-teal-50 p-3 text-xs leading-5 text-teal-900">日曆已登記的收款會自動帶入，請勿再記一次。這裡的手動收入不會修改訂單付款狀態。</p>}
 </fieldset>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}{pending&&!busy&&<p className="text-xs text-slate-500">保留原紀錄重試，不會重複記帳。</p>}<div className="flex justify-end gap-2">{!pending&&<Button type="button" variant="outline" disabled={busy} onClick={onClose}>取消</Button>}<Button type="submit" disabled={busy} className="bg-teal-800 hover:bg-teal-900">{busy?'儲存並確認中…':pending?'重試原紀錄':'儲存'+(kind==='expense'?'支出':'收入')}</Button></div>
 </form></DialogContent></Dialog>;
}
function VoidForm({report,entry,onClose,onSaved}:{report:FinanceReport;entry:FinanceEntry;onClose:()=>void;onSaved:()=>void}){const [reason,setReason]=useState('');const {busy,error,pending,save}=useFinanceSave(report,onSaved);return <Dialog open onOpenChange={open=>!open&&!busy&&!pending&&onClose()}><DialogContent showCloseButton={!busy&&!pending}><DialogTitle>作廢記帳紀錄</DialogTitle><DialogDescription>原紀錄會保留，但不再列入收支統計。</DialogDescription><p className="text-sm">{entry.description} · {money(entry.amount_cents)}</p><form className="space-y-4" onSubmit={e=>{e.preventDefault();void save({action:'void',entry_id:entry.id,reason});}}><label className="block text-sm">作廢原因<input required maxLength={300} disabled={busy||!!pending} value={reason} onChange={e=>setReason(e.target.value)} className={inputClass}/></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2">{!pending&&<Button type="button" variant="outline" disabled={busy} onClick={onClose}>取消</Button>}<Button type="submit" disabled={busy}>{busy?'確認中…':pending?'重試原操作':'確認作廢'}</Button></div></form></DialogContent></Dialog>;}
