"use client";
import {useIntlLocale} from "@/components/i18n/language-provider";
import {useT} from "@/components/i18n/language-provider";
import {useFinanceSave} from './use-finance-save';
import Link from 'next/link';
import {useRouter,useSearchParams} from 'next/navigation';
import {useEffect,useMemo,useState} from 'react';
import {ArrowDownLeft,ArrowUpRight,Plus,ChevronLeft,ChevronRight,RefreshCw,Receipt,Wallet,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {EXPENSE_CATEGORIES,INCOME_CATEGORIES,METHODS,categoryLabel,summarize,type FinanceEntry,type FinanceKind,type FinanceReport} from '@/lib/finance-model';
import {RevenueCharts,InteractiveDonut,Receivables,RecurringPanel,RecurringForm,PayoutRulesForm} from './finance-receivables';
import {PLATFORMS,revenueSummary,type FinanceOrder,type DueExpense} from '@/lib/finance-model';
const money=(cents:number,locale="zh-TW")=>new Intl.NumberFormat(locale,{style:'currency',currency:'TWD',maximumFractionDigits:cents%100?2:0}).format(cents/100);
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const stageLabel:Record<string,string>={deposit:'訂金',balance:'尾款',full:'全額',other:'其他款項'};
const COLORS=['#264653','#2a9d8f','#80b6a4','#d7ad58','#c67e59','#7d83a5','#a3aab5','#80926d','#b69b86','#d2d6d9'];
const expenseColor=(id:string)=>COLORS[Math.max(0,Object.keys(EXPENSE_CATEGORIES).indexOf(id))%COLORS.length];
const box='min-w-0 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm';
const inputClass='mt-1.5 block w-full min-w-0 rounded-lg border bg-white px-3 py-2.5 text-sm';
export function FinanceWorkspace({view}:{view:'overview'|'bookkeeping'}){
const uiLocale = useIntlLocale();

  const uiText = useT();

 const router=useRouter(),query=useSearchParams();
 const rawMonth=query.get('month')??today().slice(0,7);
 const month=/^(20\d{2})-(0[1-9]|1[0-2])$/.test(rawMonth)?rawMonth:today().slice(0,7);
 const property=query.get('property')??'';
 const [reload,setReload]=useState(0);
 const requestKey=`${month}:${property}:${reload}`;
 const [result,setResult]=useState<{key:string;data:FinanceReport|null;error:string}|null>(null);
 const loading=result?.key!==requestKey;
 const data=loading?null:result?.data??null;
 const error=loading?'':result?.error??'';
 const [kind,setKind]=useState<FinanceKind>('expense'),[search,setSearch]=useState(''),[category,setCategory]=useState('all');
 const [formKind,setFormKind]=useState<FinanceKind|null>(null),[voidEntry,setVoidEntry]=useState<FinanceEntry|null>(null),[detail,setDetail]=useState<FinanceEntry|null>(null),[notice,setNotice]=useState('');
 useEffect(()=>{const controller=new AbortController();fetch(`/api/v1/finance?year=${month.slice(0,4)}&property=${encodeURIComponent(property)}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const response=await r.json();if(!r.ok)throw new Error(response.detail);if(!controller.signal.aborted)setResult({key:requestKey,data:response,error:''});}).catch(e=>{if(!controller.signal.aborted)setResult({key:requestKey,data:null,error:e.message});});return()=>controller.abort();},[month,property,requestKey]);
 const summary=useMemo(()=>summarize(data?.entries??[],month),[data,month]);
 const monthly=(data?.entries??[]).filter(e=>e.date.startsWith(month));
 const filtered=monthly.filter(e=>(e.kind!=='income'||e.method!=='ota')&&e.kind===kind&&(category==='all'||e.category===category)&&`${e.description} ${categoryLabel(e)} ${e.actor}`.toLowerCase().includes(search.toLowerCase()));
 function navigate(nextMonth=month,nextProperty=property,target=view){router.push(`/finance${target==='bookkeeping'?'/bookkeeping':''}?month=${nextMonth}&property=${encodeURIComponent(nextProperty||data?.property_id||'')}`);}
 function shift(n:number){const date=new Date(month+'-01T00:00:00Z');date.setUTCMonth(date.getUTCMonth()+n);navigate(date.toISOString().slice(0,7));}
 const [recurringOpen,setRecurringOpen]=useState(false),[rulesOpen,setRulesOpen]=useState(false),[receiveOrder,setReceiveOrder]=useState<FinanceOrder|undefined>(),[payDue,setPayDue]=useState<DueExpense|undefined>();
 const revenue=revenueSummary(data?.orders??[],data?.entries??[],month);
 const changed=()=>{setReload(v=>v+1);setNotice('已儲存並確認。');};
 return <div className="mx-auto max-w-7xl space-y-6 pb-8 text-slate-800">
  <header className="flex flex-wrap items-end justify-between gap-4 pt-2"><div><p className="text-xs font-semibold tracking-[.16em] text-teal-700">{uiText("FINANCE · 財務")}</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">{view==='overview'?uiText("把每一筆收支，看得清楚。"):uiText("記帳")}</h1><p className="mt-2 text-sm text-slate-500">{view==='overview'?uiText("從日常記帳，掌握旅宿的花費與收款。"):uiText("按實際收付款日期整理，每一筆都有來源與紀錄。")}</p></div><Button disabled={!data||loading} onClick={()=>{setPayDue(undefined);setFormKind('expense');}} className="h-11 bg-teal-800 px-5 text-white hover:bg-teal-900"><Plus className="size-4"/>{uiText("新增支出")}</Button></header>
  <div className="flex flex-wrap items-center justify-between gap-3 border-b pb-3"><nav className="flex gap-5 text-sm font-medium" aria-label={uiText("財務功能")}><Link className={view==='overview'?'text-teal-800 underline underline-offset-8':'text-slate-500'} href={`/finance?month=${month}&property=${property}`}>{uiText("財務首頁")}</Link><Link className={view==='bookkeeping'?'text-teal-800 underline underline-offset-8':'text-slate-500'} href={`/finance/bookkeeping?month=${month}&property=${property}`}>{uiText("記帳")}</Link><Link className="text-slate-500" href={`/finance/summary?property=${encodeURIComponent(property||data?.property_id||'')}`}>{uiText("訂單財務摘要")}</Link></nav><div className="flex flex-wrap items-center gap-2"><select aria-label={uiText("選擇記帳旅宿")} value={data?.property_id??property} disabled={!data} onChange={e=>navigate(month,e.target.value)} className="max-w-44 rounded-lg border bg-white p-2 text-sm">{data?.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="flex items-center rounded-lg border bg-white"><Button size="icon" variant="ghost" aria-label={uiText("上一個月")} disabled={month<='2020-01'} onClick={()=>shift(-1)}><ChevronLeft className="size-4"/></Button><input aria-label={uiText("記帳月份")} type="month" min="2020-01" max="2099-12" value={month} onChange={e=>e.target.value&&navigate(e.target.value)} className="w-32 bg-transparent text-sm"/><Button size="icon" variant="ghost" aria-label={uiText("下一個月")} disabled={month>='2099-12'} onClick={()=>shift(1)}><ChevronRight className="size-4"/></Button></div><Button size="icon" variant="ghost" aria-label={uiText("重新整理財務")} onClick={()=>setReload(v=>v+1)}><RefreshCw className={`size-4 ${loading?'animate-spin':''}`}/></Button></div></div>
  {notice&&<p role="status" className="text-sm text-teal-800">{uiText(notice)}</p>}
  {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{uiText(error)} <Button variant="outline" size="sm" onClick={()=>setReload(v=>v+1)}>{uiText("重試")}</Button></div>}
  {loading&&<div className={`${box} py-16 text-center text-slate-500`}>{uiText("正在核對帳本與日曆收款…")}</div>}
  {data&&!loading&&<>
   <div className="grid gap-3 sm:grid-cols-3">{[{label:'本月已收帳款',value:revenue.received,icon:ArrowDownLeft,color:'text-teal-800',hint:'本月入住訂單已收款＋其他服務收入'},{label:'本月應收帳款',value:revenue.receivable,icon:ArrowUpRight,color:'text-amber-800',hint:'本月入住訂單尚未收到的房費'},{label:'本月總收入',value:revenue.total,icon:Wallet,color:'text-slate-800',hint:'已收＋應收，未扣支出與未記錄的平台費用'}].map(m=><div key={m.label} className={box}><div className="flex justify-between text-sm text-slate-500">{uiText(m.label)}<m.icon className="size-4"/></div><p className={`mt-3 text-3xl font-semibold tabular-nums tracking-tight ${m.color}`}>{money(m.value, uiLocale)}</p><p className="mt-2 text-xs text-slate-500">{uiText(m.hint)}</p></div>)}</div>
   <p className="text-xs leading-5 text-slate-500">{uiText("本月實際入帳")}{money(summary.income-summary.ota, uiLocale)} {uiText("· 已付支出")}{money(summary.expense, uiLocale)} {uiText("· 現金收支差額")}{money(summary.income-summary.ota-summary.expense, uiLocale)}{uiText("。依收付款日期，與上方入住月份不同。來源表 done 僅代表客人付清，不等於旅宿已入帳。")}</p>
   <RevenueCharts report={data} month={month}/>
   <Receivables report={data} month={month} onReceive={order=>{setReceiveOrder(order);setFormKind('income');}} onRules={()=>setRulesOpen(true)}/>
   <RecurringPanel report={data} month={month} onNew={()=>setRecurringOpen(true)} onPay={due=>{setPayDue(due);setFormKind('expense');}} onChanged={changed}/>
   <div className="grid gap-4 lg:grid-cols-[1.4fr_1fr]"><ExpenseTrend values={summary.monthly} year={month.slice(0,4)} selected={Number(month.slice(5))}/><ExpenseDonut categories={summary.categories} total={summary.expense}/></div>
   {view==='overview'?<section className={box}><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">{uiText("本月最近收支")}</h2><button className="flex items-center gap-1 text-sm text-teal-800" onClick={()=>navigate(month,property,'bookkeeping')}>{uiText("查看記帳")}<ArrowRight className="size-4"/></button></div>{monthly.length?<EntryList entries={monthly.slice(0,6)} onSelect={setDetail}/>:<Empty onAdd={()=>setFormKind('expense')}/>}</section>:<section className={box}>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-lg bg-slate-100 p-1" role="group" aria-label={uiText("收支分類")}>{(['expense','income'] as FinanceKind[]).map(k=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setCategory('all');}} className={`rounded-md px-5 py-2 text-sm font-semibold ${kind===k?'bg-white shadow-sm':'text-slate-500'}`}>{k==='expense'?uiText("支出"):uiText("收入")}</button>)}</div>{kind==='income'&&<Button variant="outline" onClick={()=>{setReceiveOrder(undefined);setFormKind('income');}}><Plus className="size-4"/>{uiText("新增收入")}</Button>}</div>
    {kind==='income'&&<p className="mt-3 text-xs leading-5 text-slate-500">{uiText("收入按服務分類；訂金、尾款、全額是收款階段。已在日曆登記的款項會自動列入。OTA 代收尚未撥款不列已收。")}</p>}
    <div className="my-4 flex flex-wrap gap-2"><input aria-label={uiText("搜尋記帳")} placeholder={uiText("搜尋說明、分類或登記人")} value={search} onChange={e=>setSearch(e.target.value)} className="min-w-0 flex-1 rounded-lg border p-2.5 text-sm"/><select aria-label={uiText("篩選記帳分類")} value={category} onChange={e=>setCategory(e.target.value)} className="max-w-40 rounded-lg border bg-white p-2 text-sm"><option value="all">{uiText("全部分類")}</option>{Object.entries(kind==='expense'?EXPENSE_CATEGORIES:INCOME_CATEGORIES).map(([key,label])=><option key={key} value={key}>{uiText(label)}</option>)}</select></div>
    {filtered.length?<EntryList entries={filtered} onSelect={setDetail}/>:<Empty onAdd={()=>setFormKind(kind)} filtered={!!search||category!=='all'} kind={kind}/>}
   </section>}
   <p className="text-right text-xs text-slate-400">{uiText("更新於")}{new Date(data.updated_at).toLocaleString(uiLocale,{timeZone:'Asia/Taipei',hour12:false})} {uiText("· TWD 新台幣")}</p>
  </>}
  {data&&formKind&&<EntryForm initialOrder={formKind==='income'?receiveOrder:undefined} due={formKind==='expense'?payDue:undefined} kind={formKind} report={data} month={month} onClose={()=>setFormKind(null)} onSaved={()=>{setFormKind(null);changed();}}/>}
  {data&&recurringOpen&&<RecurringForm report={data} onClose={()=>setRecurringOpen(false)} onSaved={()=>{setRecurringOpen(false);changed();}}/>}
  {data&&rulesOpen&&<PayoutRulesForm report={data} onClose={()=>setRulesOpen(false)} onSaved={()=>{setRulesOpen(false);changed();}}/>}
  <Dialog open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><DialogContent className="max-h-[85dvh] overflow-y-auto"><DialogTitle>{uiText("記帳明細")}</DialogTitle><DialogDescription>{uiText("查看這筆收支的來源與登記紀錄。")}</DialogDescription>{detail&&<div className="space-y-3 text-sm"><p className="text-3xl font-semibold">{money(detail.amount_cents, uiLocale)}</p><p>{detail.date.replaceAll('-','/')} · {uiText(categoryLabel(detail))} · {uiText(METHODS[detail.method])}</p><p className="whitespace-pre-wrap break-words">{detail.description}</p><p>{uiText("來源：")}{detail.source==='calendar'?uiText("日曆付款自動帶入"):uiText("手動記帳")}{detail.stage?` · ${stageLabel[detail.stage]??''}`:''}</p><p>{uiText("登記人：")}{detail.actor}</p><p className="text-xs text-slate-500">{uiText("登記時間：")}{new Date(detail.created_at).toLocaleString(uiLocale,{timeZone:'Asia/Taipei',hour12:false})}</p>{detail.status==='void'?<p className="rounded-lg bg-amber-50 p-3">{uiText("已作廢：")}{detail.void_reason} · {detail.void_actor}</p>:detail.source==='manual'?<Button variant="outline" onClick={()=>{setVoidEntry(detail);setDetail(null);}}>{uiText("作廢這筆紀錄")}</Button>:<p className="text-xs text-slate-500">{uiText("這筆來自日曆付款，財務頁不會重複新增或覆寫。")}</p>}</div>}</DialogContent></Dialog>
  {data&&voidEntry&&<VoidForm report={data} entry={voidEntry} onClose={()=>setVoidEntry(null)} onSaved={()=>{setVoidEntry(null);changed();}}/>}
 </div>;
}
function EntryList({entries,onSelect}:{entries:FinanceEntry[];onSelect:(entry:FinanceEntry)=>void}){
const uiLocale = useIntlLocale();

  const uiText = useT();
return <div className="divide-y">{entries.map(e=><button key={e.id} onClick={()=>onSelect(e)} className="flex w-full items-center gap-3 py-3.5 text-left hover:bg-slate-50"><span className={`flex size-9 shrink-0 items-center justify-center rounded-xl ${e.kind==='income'?'bg-teal-50 text-teal-700':'bg-slate-100 text-slate-500'}`}>{e.kind==='income'?<ArrowDownLeft className="size-4"/>:<ArrowUpRight className="size-4"/>}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{e.description||uiText(categoryLabel(e))}</span><span className="mt-1 block text-xs text-slate-500">{e.date.slice(5).replace('-','/')} · {uiText(categoryLabel(e))}{e.source==='calendar'?(e.method==='ota'?' · 平台代收（尚未入帳）':' · 日曆收款'):''}{e.stage?` · ${stageLabel[e.stage]}`:''}{e.status==='void'?uiText(" · 已作廢"):''}</span></span><span className={`shrink-0 text-sm font-semibold tabular-nums ${e.status==='void'?'text-slate-400 line-through':e.kind==='income'?'text-teal-800':'text-slate-800'}`}>{e.kind==='income'?'+':'−'}{money(e.amount_cents, uiLocale)}</span></button>)}</div>;}
function Empty({onAdd,filtered=false,kind='expense'}:{onAdd:()=>void;filtered?:boolean;kind?:FinanceKind}){
  const uiText = useT();
return <div className="py-12 text-center"><Receipt className="mx-auto mb-3 size-8 text-slate-300"/><p className="font-medium">{filtered?uiText("沒有符合條件的紀錄"):uiText("這個月還沒有記帳資料")}</p><p className="mt-2 text-sm text-slate-500">{filtered?uiText("試著換一個分類或搜尋文字。"):uiText("新增第一筆，開始累積清楚的收支紀錄。")}</p>{!filtered&&<Button variant="outline" className="mt-5" onClick={onAdd}><Plus className="size-4"/>{kind==='expense'?uiText("新增支出"):uiText("新增收入")}</Button>}</div>;}
function ExpenseTrend({values,year,selected}:{values:{month:number;expense:number}[];year:string;selected:number}){
const uiLocale = useIntlLocale();

  const uiText = useT();
const [hover,setHover]=useState<string|null>(null);const max=Math.max(...values.map(v=>v.expense),100);return <section className={box}><h2 className="font-semibold">{year} {uiText("年支出趨勢")}</h2><p className="mt-1 text-xs text-slate-500">{uiText("依支出發生月份 · 全年已登記")}{money(values.reduce((s,v)=>s+v.expense,0), uiLocale)}</p><div className="relative mt-6"><div className="flex h-44 items-end gap-2 border-b border-slate-200 px-1" role="img" aria-label={values.map(v=>`${v.month}月 ${money(v.expense, uiLocale)}`).join('、')}>{values.map(v=><div className="flex h-full min-w-0 flex-1 items-end" key={v.month}><button aria-label={uiText("{0}月支出 {1}", [v.month,money(v.expense, uiLocale)])} onFocus={()=>setHover(`${v.month}月：${money(v.expense, uiLocale)}`)} onMouseEnter={()=>setHover(`${v.month}月：${money(v.expense, uiLocale)}`)} onClick={()=>setHover(`${v.month}月：${money(v.expense, uiLocale)}`)} title={uiText("{0}月：{1}", [v.month,money(v.expense, uiLocale)])} className={`w-full rounded-t-md ${v.month===selected?'bg-teal-800':'bg-teal-200'}`} style={{height:v.expense?`${Math.max(2,v.expense/max*100)}%`:'2px'}}/></div>)}</div><div className="mt-2 flex gap-2 px-1 text-center text-[10px] text-slate-500">{values.map(v=><span className="min-w-0 flex-1" key={v.month}>{v.month}{uiText("月")}</span>)}</div></div><p role="status" className="mt-3 min-h-4 text-xs text-slate-600">{uiText(hover??'滑過長條或點選月份查看金額。')}</p>{values.every(v=>!v.expense)&&<p className="mt-4 text-xs text-slate-400">{uiText("尚無支出紀錄；新增後會呈現每月趨勢。")}</p>}<details className="mt-4 text-xs text-slate-500"><summary className="cursor-pointer">{uiText("查看每月金額")}</summary><div className="mt-2 grid grid-cols-3 gap-2">{values.map(v=><span key={v.month}>{v.month}{uiText("月")}{money(v.expense, uiLocale)}</span>)}</div></details></section>;}
function ExpenseDonut({categories}:{categories:{id:string;label:string;amount:number}[];total:number}){
  const uiText = useT();
return <section className={box}><h2 className="font-semibold">{uiText("本月支出分布")}</h2><p className="mb-5 mt-1 text-xs text-slate-500">{uiText("滑過圓餅區塊或點選，查看金額與占比")}</p><InteractiveDonut label={uiText("本月支出")} items={categories.map(c=>({...c,color:expenseColor(c.id)}))}/></section>;}
function EntryForm({kind,report,month,onClose,onSaved,initialOrder,due}:{kind:FinanceKind;report:FinanceReport;month:string;onClose:()=>void;onSaved:()=>void;initialOrder?:FinanceOrder;due?:DueExpense}){
const uiLocale = useIntlLocale();

  const uiText = useT();

 const [category,setCategory]=useState(kind==='expense'?(due?.category??'laundry'):'lodging'),[amount,setAmount]=useState(due?String(due.amount_cents/100):initialOrder?String(initialOrder.receivable/100):''),[date,setDate]=useState(due?today():month===today().slice(0,7)?today():month+'-01'),[description,setDescription]=useState(due?.description??(initialOrder?`${PLATFORMS[initialOrder.platform]}房費`:'')),[method,setMethod]=useState<string>(due?.method??'bank_transfer'),[stage,setStage]=useState('');
 const [platform,setPlatform]=useState(initialOrder?.platform??'direct'),[allocations,setAllocations]=useState<Record<string,string>>(initialOrder?{[initialOrder.id]:String(initialOrder.receivable/100)}:{}),[orderSearch,setOrderSearch]=useState('');
 const {busy,error,pending,save}=useFinanceSave(report,onSaved);
 return <Dialog open onOpenChange={open=>!open&&!busy&&!pending&&onClose()}><DialogContent showCloseButton={!busy&&!pending} className="max-h-[90dvh] overflow-y-auto"><DialogTitle>{kind==='expense'?uiText("新增支出"):uiText("新增收入")}</DialogTitle><DialogDescription>{report.properties.find(p=>p.id===report.property_id)?.name} {uiText("· 依實際收付款日期記錄")}</DialogDescription><form onSubmit={e=>{e.preventDefault();void save({action:'create',kind,category,amount:Number(amount),date,description,method,stage,year:Number(date.slice(0,4)),...(kind==='income'&&category==='lodging'?{platform,allocations:Object.entries(allocations).map(([order_id,v])=>({order_id,amount_cents:Math.round(Number(v)*100)}))}:{}),...(kind==='expense'&&due?{recurrence_id:due.rule_id,occurrence:due.date}:{} )});}} className="space-y-4">
 <fieldset disabled={busy||!!pending} className="grid min-w-0 gap-4 disabled:opacity-60"><div className="grid min-w-0 grid-cols-2 gap-3"><label className="min-w-0 text-sm">{uiText("金額（元）")}<input autoFocus required type="number" min="0.01" max="10000000" step="0.01" placeholder="0" value={amount} onChange={e=>setAmount(e.target.value)} className={inputClass}/></label><label className="min-w-0 text-sm">{kind==='expense'?uiText("付款"):uiText("收款")}{uiText("日期")}<input required type="date" min="2020-01-01" max={today()} value={date} onChange={e=>setDate(e.target.value)} className={inputClass}/></label></div>
 <label className="text-sm">{uiText("分類")}<select value={category} onChange={e=>setCategory(e.target.value)} className={inputClass}>{Object.entries(kind==='expense'?EXPENSE_CATEGORIES:INCOME_CATEGORIES).map(([k,v])=><option key={k} value={k}>{uiText(v)}</option>)}</select></label>
 <label className="text-sm">{kind==='expense'?uiText("支出說明（選填）"):uiText("收入說明")}<input required={kind==='income'} maxLength={500} placeholder={kind==='expense'?uiText("例如：9 月床單送洗"):uiText("例如：早餐加購 2 份")} value={description} onChange={e=>setDescription(e.target.value)} className={inputClass}/></label>
 <label className="text-sm">{uiText("付款方式")}<select value={method} onChange={e=>setMethod(e.target.value)} className={inputClass}>{Object.entries(METHODS).filter(([key])=>key!=='ota').map(([key,label])=><option key={key} value={key}>{uiText(label)}</option>)}</select></label>
 {kind==='income'&&category==='lodging'&&<div className="space-y-3 rounded-lg border p-3"><label className="block text-sm">{uiText("房費來源")}<select className={inputClass} value={platform} onChange={e=>{setPlatform(e.target.value);setAllocations({});setAmount('');setDescription(`${PLATFORMS[e.target.value]}房費`);}}>{Object.entries(PLATFORMS).map(([k,v])=><option key={k} value={k}>{uiText(v)}{uiText("房費")}</option>)}</select></label><input aria-label={uiText("搜尋待入帳訂單")} className={inputClass} placeholder={uiText("入住日期、房號或訂單 ID")} value={orderSearch} onChange={e=>setOrderSearch(e.target.value)}/><p className="text-xs text-slate-500">{uiText("選擇本次入帳的訂單；可多選，也可修改各筆本次收款金額。分配合計須等於上方金額。")}</p><div className="max-h-52 space-y-3 overflow-y-auto">{report.orders.filter(o=>o.platform===platform&&o.receivable>0&&`${o.check_in} ${o.rooms.join(' ')} ${o.id}`.includes(orderSearch)).map(o=><div key={o.id} className="text-xs"><label className="flex flex-wrap gap-2"><input type="checkbox" checked={o.id in allocations} onChange={e=>{const next={...allocations};if(e.target.checked)next[o.id]=String(o.receivable/100);else delete next[o.id];setAllocations(next);setAmount(String(Object.values(next).reduce((s,v)=>s+Number(v),0)));}}/><span>{o.check_in.replaceAll('-','/')} · {o.rooms.join('、')} {uiText("· 應收")}{money(o.receivable, uiLocale)}{o.eligible_date?uiText(" · {0} {1}", [o.platform==='agoda'?'可請款':'預計入帳',o.eligible_date]):''}</span></label>{o.id in allocations&&<label className="mt-1 block">{uiText("本次收款")}<input required aria-label={uiText("{0} {1} 本次收款", [o.check_in,o.rooms.join('、')])} type="number" step="0.01" min="0.01" max={o.receivable/100} className={inputClass} value={allocations[o.id]} onChange={e=>{const next={...allocations,[o.id]:e.target.value};setAllocations(next);setAmount(String(Object.values(next).reduce((s,v)=>s+Number(v),0)));}}/></label>}</div>)}</div><p className="text-xs">{uiText("已選")}{Object.keys(allocations).length} {uiText("筆 · 本次")}{money(Object.values(allocations).reduce((s,v)=>s+Math.round(Number(v)*100),0), uiLocale)}</p></div>}
 {kind==='income'&&category==='lodging'&&<label className="text-sm">{uiText("收款階段")}<select value={stage} onChange={e=>setStage(e.target.value)} className={inputClass}><option value="">{uiText("未指定")}</option>{Object.entries(stageLabel).map(([k,v])=><option key={k} value={k}>{uiText(v)}</option>)}</select></label>}
 {kind==='income'&&<p className="rounded-lg bg-teal-50 p-3 text-xs leading-5 text-teal-900">{uiText("日曆已登記的收款會自動帶入，請勿再記一次。住宿收入必須對應訂單，金額會扣抵應收；請確認這是實際收到的款項。")}</p>}
 </fieldset>{error&&<p role="alert" className="text-sm text-red-700">{uiText(error)}</p>}{pending&&!busy&&<p className="text-xs text-slate-500">{uiText("保留原紀錄重試，不會重複記帳。")}</p>}<div className="flex justify-end gap-2">{!pending&&<Button type="button" variant="outline" disabled={busy} onClick={onClose}>{uiText("取消")}</Button>}<Button type="submit" disabled={busy} className="bg-teal-800 hover:bg-teal-900">{busy?uiText("儲存並確認中…"):pending?uiText("重試原紀錄"):uiText(kind==='expense'?'儲存支出':'儲存收入')}</Button></div>
 </form></DialogContent></Dialog>;
}
function VoidForm({report,entry,onClose,onSaved}:{report:FinanceReport;entry:FinanceEntry;onClose:()=>void;onSaved:()=>void}){
const uiLocale = useIntlLocale();

  const uiText = useT();
const [reason,setReason]=useState('');const {busy,error,pending,save}=useFinanceSave(report,onSaved);return <Dialog open onOpenChange={open=>!open&&!busy&&!pending&&onClose()}><DialogContent showCloseButton={!busy&&!pending}><DialogTitle>{uiText("作廢記帳紀錄")}</DialogTitle><DialogDescription>{uiText("原紀錄會保留，但不再列入收支統計。")}</DialogDescription><p className="text-sm">{entry.description} · {money(entry.amount_cents, uiLocale)}</p><form className="space-y-4" onSubmit={e=>{e.preventDefault();void save({action:'void',entry_id:entry.id,reason,year:Number(entry.date.slice(0,4))});}}><label className="block text-sm">{uiText("作廢原因")}<input required maxLength={300} disabled={busy||!!pending} value={reason} onChange={e=>setReason(e.target.value)} className={inputClass}/></label>{error&&<p role="alert" className="text-sm text-red-700">{uiText(error)}</p>}<div className="flex justify-end gap-2">{!pending&&<Button type="button" variant="outline" disabled={busy} onClick={onClose}>{uiText("取消")}</Button>}<Button type="submit" disabled={busy}>{busy?uiText("確認中…"):pending?uiText("重試原操作"):uiText("確認作廢")}</Button></div></form></DialogContent></Dialog>;}
