"use client";
import {useEffect,useState} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import Link from 'next/link';
import {useT} from '@/components/i18n/language-provider';
import {useFinanceSave} from './use-finance-save';
import {METHODS,taipeiDate,type FinanceReport} from '@/lib/finance-model';
export function PaymentAccountSettings(){
 const t=useT(),query=useSearchParams(),router=useRouter();const property=query.get('property')??'',year=Number(taipeiDate().slice(0,4));
 const [reload,setReload]=useState(0),[result,setResult]=useState<{key:string;data?:FinanceReport;error?:string}>();const key=`${property}:${reload}`;
 useEffect(()=>{const c=new AbortController();fetch(`/api/v1/finance?property=${encodeURIComponent(property)}&year=${year}`,{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.detail);if(!c.signal.aborted)setResult({key,data:d});}).catch(e=>{if(!c.signal.aborted)setResult({key,error:e.message});});return()=>c.abort();},[property,year,key]);
 const data=result?.key===key?result.data:undefined;
 return <section className="mx-auto max-w-xl space-y-5"><Link href="/settings" className="text-sm underline">{t('設定')}</Link><h1 className="text-2xl font-semibold">{t('付款帳戶')}</h1><p className="text-sm text-slate-500">{t('只需填寫末碼，供此旅宿記帳時辨認。')}</p>{result?.key===key&&result.error&&<p role="alert">{t(result.error)} <button onClick={()=>setReload(n=>n+1)}>{t('重試')}</button></p>}{data?<><label className="block text-sm">{t('旅宿')}<select className="mt-1 block w-full rounded-lg border p-3" value={data.property_id} onChange={e=>router.push(`/settings/payment-accounts?property=${e.target.value}`)}>{data.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><ul className="space-y-2">{data.payment_accounts?.map(a=><li className="rounded-lg border p-3" key={a.id}>{t(METHODS[a.method])} · {a.name?`${a.name} · `:''}•• {a.last_digits}</li>)}</ul><AccountForm key={key} report={data} onSaved={()=>setReload(n=>n+1)}/></>:!result?.error&&<p>{t('載入中…')}</p>}</section>;
}
function AccountForm({report,onSaved}:{report:FinanceReport;onSaved:()=>void}){const t=useT();const [method,setMethod]=useState('credit_card'),[digits,setDigits]=useState(''),[name,setName]=useState('');const {save,busy,error,pending}=useFinanceSave(report,onSaved);const length=method==='credit_card'?4:5;
 return <form className="space-y-4 rounded-xl border p-4" onSubmit={e=>{e.preventDefault();void save({action:'payment_account_create',method,last_digits:digits,name});}}><h2 className="font-medium">{t('新增付款帳戶')}</h2><fieldset disabled={busy||!!pending} className="space-y-3"><label className="block text-sm">{t('付款方式')}<select className="mt-1 block w-full rounded-lg border p-3" value={method} onChange={e=>{setMethod(e.target.value);setDigits('');}}><option value="credit_card">{t('信用卡')}</option><option value="bank_transfer">{t('轉帳帳戶')}</option></select></label><label className="block text-sm">{t(method==='credit_card'?'信用卡後 4 碼':'帳戶後 5 碼')}<input className="mt-1 block w-full rounded-lg border p-3" inputMode="numeric" autoComplete="off" required minLength={length} maxLength={length} pattern={`[0-9]{${length}}`} value={digits} onChange={e=>setDigits(e.target.value)}/></label><label className="block text-sm">{t('名稱（選填）')}<input className="mt-1 block w-full rounded-lg border p-3" maxLength={50} value={name} onChange={e=>setName(e.target.value)} /></label></fieldset>{error&&<p role="alert" className="text-sm text-red-700">{t(error)}</p>}<button disabled={busy} className="w-full rounded-lg bg-teal-800 p-3 text-white" type="submit">{t(busy?'儲存中…':pending?'重試原紀錄':'儲存')}</button></form>;
}
