import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { NextRequest } from 'next/server';
import { localRedis } from './helpers/redis-command.mjs';
import { RedisCustomerStore } from '../src/lib/customer-workspaces/store.ts';
import { login, sessionFor, CUSTOMER_COOKIE } from '../src/lib/customer-workspaces/auth.ts';
import { createWorkspace, loadWorkspace } from '../src/lib/customer-workspaces/service.ts';
import { GET, POST } from '../src/app/api/arrival-reminders/route.ts';
import { claimReminder, acknowledgeReminder } from '../src/lib/arrival-reminders/service.ts';
const integration=process.env.CALENDAR_TEST_REDIS_PORT?test:test.skip;
integration('real Redis + routes: new tenant, scoped arrivals, handled persistence, revoked role, same-origin and anonymous refusal',async t=>{
  process.env.CUSTOMER_WORKSPACE_NAMESPACE='arrival-tests:'+randomUUID();
  process.env.UPSTASH_REDIS_REST_URL='https://arrival-redis.test.invalid';process.env.UPSTASH_REDIS_REST_TOKEN='synthetic';
  process.env.CUSTOMER_WORKSPACES_ENABLED='true';process.env.CUSTOMER_SELF_SIGNUP_PREVIEW='true';process.env.CUSTOMER_SESSION_SECRET='synthetic-arrival-route-session-secret-32';
  t.mock.method(globalThis,'fetch',async(url,options)=>{assert.equal(url,process.env.UPSTASH_REDIS_REST_URL);return Response.json({result:await localRedis(JSON.parse(options.body))});});
  const store=new RedisCustomerStore(),password='Synthetic route password 2026!';
  const account=await login(store,{mode:'register',email:'arrival.owner@example.test',password,confirmPassword:password});
  await createWorkspace(store,account,{name:'Synthetic arrival inn',slug:'arrival-test-inn',kind:'rooms',rooms:['101','102'],requestKey:randomUUID()});
  const saved=await loadWorkspace(store,account.id,'arrival-test-inn'),workspace=saved.workspace,property=workspace.properties[0];
  const day=new Date(Date.now()+8*3600_000).toISOString().slice(0,10),end=new Date(Date.parse(day)+86400000).toISOString().slice(0,10);
  workspace.bookings=[{id:randomUUID(),propertyId:property.id,guestName:'Synthetic Guest',checkIn:day,checkOut:end,roomIds:[property.rooms[0].id],notes:'需要嬰兒床',status:'confirmed'}];
  await store.commit([{key:`workspace:${workspace.id}`,before:saved.raw,after:workspace}]);
  const url=`https://app.test/api/arrival-reminders?workspace=${workspace.slug}&property=${property.id}`;
  const cookie=`${CUSTOMER_COOKIE}=${sessionFor(account)}`;
  const request=(method='GET',input,extra={})=>new NextRequest(url,{method,headers:{cookie,...(input?{'content-type':'application/json',origin:'https://app.test'}:{}),...extra},...(input?{body:JSON.stringify(input)}:{})});
  assert.equal((await GET(new NextRequest(url))).status,401);
  const first=await GET(request());assert.equal(first.status,200);assert.match(first.headers.get('cache-control'),/no-store/);
  const list=await first.json(),item=list.arrivals[0];assert.equal(item.notes,'需要嬰兒床');
  assert.equal((await POST(request('POST',{action:'handled',id:item.id,fingerprint:item.fingerprint},{origin:'https://evil.test'}))).status,403);
  assert.equal((await POST(request('POST',{action:'handled',id:item.id,fingerprint:item.fingerprint}))).status,200);
  assert.ok((await (await GET(request())).json()).arrivals[0].handledAt);
  const old=await store.read(`workspace:${workspace.id}`);workspace.members[0].role='viewer_no_price';
  await store.commit([{key:`workspace:${workspace.id}`,before:old.raw,after:workspace}]);
  const denied=await GET(request());assert.equal(denied.status,403);assert.ok(!JSON.stringify(await denied.json()).includes('嬰兒床'));
});
integration('real Redis CAS: simultaneous delivery, new store instance recovery and receipt identity',async t=>{
  process.env.CUSTOMER_WORKSPACE_NAMESPACE='arrival-tests:'+randomUUID();process.env.UPSTASH_REDIS_REST_URL='https://arrival-redis.test.invalid';process.env.UPSTASH_REDIS_REST_TOKEN='synthetic';
  t.mock.method(globalThis,'fetch',async(url,options)=>{assert.equal(url,process.env.UPSTASH_REDIS_REST_URL);return Response.json({result:await localRedis(JSON.parse(options.body))});});
  const data={scope:'legacy:sweetfun',day:'2026-10-10',checkedAt:'2026-10-10T01:00:00Z',propertyName:'Synthetic',arrivals:[{id:randomUUID(),fingerprint:'a'.repeat(64),guest:'Synthetic',rooms:['101'],notes:'測試備註',checkIn:'2026-10-10',checkOut:'2026-10-11',href:'/calendar'}]};
  const now=new Date(data.checkedAt),recipient='U'+'a'.repeat(32);
  const responses=await Promise.all(Array.from({length:8},()=>claimReminder(new RedisCustomerStore(),'worker','target',recipient,randomUUID(),data,now)));
  const jobs=responses.flatMap(r=>r.jobs);assert.equal(jobs.length,1);
  const job=jobs[0];
  assert.equal((await claimReminder(new RedisCustomerStore(),'worker','target',recipient,job.attemptId,data,now)).jobs[0].id,job.id);
  await acknowledgeReminder(new RedisCustomerStore(),'worker','target',data.day,job.attemptId,job.id,'sent','synthetic-provider-receipt',now);
  assert.equal((await claimReminder(new RedisCustomerStore(),'worker','target',recipient,randomUUID(),data,now)).jobs.length,0);
});
