import test from 'node:test';
import assert from 'node:assert/strict';
import { checkRows,prepareReceipt,paymentStatus,canRecord,appendReceipt,readLedger } from '../src/lib/os-payments.ts';
const actor={id:'admin1',displayName:'測試管理員',role:'admin',viewPrices:true,allProperties:false,propertyIds:['sweetfun']};
const rows=[{id:'r1',property_id:'sweetfun',order_id:'SF-test',room_id:'101',room_number:'101',check_in:'2026-09-08',check_out:'2026-09-09',room_rate:2000,payment_status:'unknown',reservation_status:'confirmed'}];
const check=checkRows(rows,'sweetfun','SF-test');
const now='2026-09-08T00:00:00.000Z';
const input={amount:500,payment_type:'deposit',payment_method:'cash',received_at:now,note:'',request_id:'00000000-0000-4000-8000-000000000001',settles_room:false,expected_version:0,source_version:check.source_version};
test('scope and role enforcement includes no-price and offland',()=>{for(const a of [{...actor,role:'viewer'},{...actor,viewPrices:false},{...actor,propertyIds:['offland']}]){assert.equal(canRecord(a,'sweetfun'),false);assert.throws(()=>prepareReceipt(input,check,a,now),/FORBIDDEN/);}});
test('amount, method, time and explicit settlement validation',()=>{for(const patch of [{amount:0},{amount:-1},{amount:0.001},{amount:NaN},{payment_method:'invalid'},{received_at:'2026-09-09T00:00:00Z'},{payment_type:'balance'},{payment_type:'other',settles_room:true}])assert.throws(()=>prepareReceipt({...input,...patch},check,actor,now),/INVALID_INPUT/);});
test('deposit, balance, other and source paid remain distinct',()=>{const receipt=prepareReceipt(input,check,actor,now);assert.equal(paymentStatus({...check,ledger:{version:1,receipts:[receipt]}}),'deposit');assert.equal(paymentStatus({...check,ledger:{version:1,receipts:[{...receipt,payment_type:'other'}]}}),'unknown');assert.equal(paymentStatus({...check,ledger:{version:1,receipts:[{...receipt,payment_type:'balance',settles_room:true}]}}),'paid');assert.equal(paymentStatus({...check,source_paid:true}),'paid');});
test('same idempotency key retries original receipt, changed payload denied',()=>{const r=prepareReceipt(input,check,actor,now);const next={...check,ledger:{version:1,receipts:[r]}};assert.equal(prepareReceipt(input,next,actor,now).id,r.id);assert.throws(()=>prepareReceipt({...input,amount:501},next,actor,now),/IDEMPOTENCY_CONFLICT/);});
test('stale versions fail; changed source invalidates settlement',()=>{assert.throws(()=>prepareReceipt({...input,expected_version:2},check,actor,now),/VERSION_CONFLICT/);const changed=checkRows([{...rows[0],room_rate:2200}],'sweetfun','SF-test');assert.notEqual(changed.source_version,check.source_version);assert.throws(()=>prepareReceipt(input,changed,actor,now),/VERSION_CONFLICT/);assert.equal(paymentStatus({...changed,ledger:{version:1,receipts:[{...prepareReceipt(input,check,actor,now),settles_room:true}]}}),'deposit');});
test('complete multi-room order check is stable regardless row order',()=>{const second={...rows[0],id:'r2',room_id:'102',room_number:'102'};const a=checkRows([...rows,second],'sweetfun','SF-test');assert.equal(a.total,4000);assert.equal(a.source_version,checkRows([second,...rows],'sweetfun','SF-test').source_version);assert.throws(()=>checkRows([{...rows[0],source_conflict:true}],'sweetfun','SF-test'),/SOURCE_CONFLICT/);});
test('persistent CAS rejects concurrent append and readback supports retries',async()=>{
 const original=global.fetch;process.env.KV_REST_API_URL='https://test.invalid';process.env.KV_REST_API_TOKEN='test';const db=new Map();
 global.fetch=async(url,options)=>{const c=JSON.parse(options.body);let result=null;if(c[0]==='GET')result=db.get(c[1])??null;if(c[0]==='SET'){db.set(c[1],c[2]);result='OK';}if(c[0]==='EVAL'){if((db.get(c[3])??'')===c[5]){db.set(c[3],c[6]);db.set(c[4],c[7]);result=1;}else result=0;}return Response.json({result});};
 try{const r=prepareReceipt(input,check,actor,now);await appendReceipt(check,null,r);assert.equal((await readLedger('sweetfun','SF-test')).ledger.receipts.length,1);await assert.rejects(()=>appendReceipt(check,null,{...r,id:'different'}),/VERSION_CONFLICT/);const current=await readLedger('sweetfun','SF-test');await appendReceipt({...check,ledger:current.ledger},current.raw,r);assert.equal((await readLedger('sweetfun','SF-test')).ledger.receipts.length,1);assert.ok([...db.values()].some(v=>JSON.parse(v).status==='completed'));}finally{global.fetch=original;}
});
test('full payment records a distinct receipt and explicit settlement',()=>{const r=prepareReceipt({...input,payment_type:'full',amount:2000,settles_room:true},check,actor,now);assert.equal(r.payment_type,'full');assert.equal(paymentStatus({...check,ledger:{version:1,receipts:[r]}}),'paid');assert.throws(()=>prepareReceipt({...input,payment_type:'full',settles_room:false},check,actor,now),/INVALID_INPUT/);});
test('calendar receipt audit records server identity, time and source version without nested secrets',()=>{
 const r=prepareReceipt(input,check,{...actor,email:'admin@example.test'},now),e=r.audit;
 assert.equal(e.action,'calendar_payment_recorded');assert.equal(e.actor_email,'admin@example.test');assert.equal(e.at,now);assert.equal(e.after.amount,500);assert.equal(e.after.order_id,check.order_id);assert.equal(e.after.request_hash,undefined);assert.equal(e.after.audit,undefined);assert.equal(e.source_version,check.source_version);assert.equal(e.version_before,0);assert.equal(e.version_after,1);
 assert.deepEqual(prepareReceipt(input,{...check,ledger:{version:1,receipts:[r]}},actor,now).audit,e);
});
