import test from 'node:test';import assert from 'node:assert/strict';import{createRelay,CAS,REDEEM}from '../../src/lib/host-agents/relay.mjs';
function setup(options={}){let time=Date.now();const values=new Map();const redis=async c=>{const [op,key,...a]=c;if(op==='GET')return values.get(key)||null;if(op==='SET'){if(a.includes('NX')&&values.has(key))return null;values.set(key,a[0]);return 'OK'}if(op==='EVAL'&&key===CAS){const [,k,raw,next]=a;if((values.get(k)||'')!==raw)return 0;values.set(k,next);return 1}if(op==='EVAL'&&key===REDEEM){const [,pair,used,token,host,raw,flag,tokenValue,,record,old]=a;if(values.get(pair)!==raw||values.has(used)||(values.get(host)||'')!==old)return 0;values.delete(pair);values.set(used,flag);values.set(token,tokenValue);values.set(host,record);return 1}throw Error('unsupported '+op)};return{values,relay:createRelay(redis,()=>time,{secret:"s".repeat(64),...options}),advance:ms=>time+=ms,now:()=>time};}
let seq=0;const nonce=()=>('nonce-'+(++seq)).padEnd(24,'x');
async function pair(f){const p=await f.relay.owner('owner','pairing');const n=nonce();const t=await f.relay.host('pairing/redeem',new Headers({'x-protocol-version':'1.0','x-request-nonce':n}),{protocol_version:'1.0',pairing_code:p.pairing_code,host_id:'my-host',agent_id:'bnb-customer-service',property_id:'sweetfun',nonce:n});return {p,t};}
function req(t,extra={}){const n=nonce(),b={protocol_version:'1.0',host_id:t.host_id,agent_id:t.agent_id,property_id:t.property_id,...extra,nonce:n};return [new Headers({authorization:'Bearer '+t.host_token,'x-host-id':t.host_id,'x-agent-id':t.agent_id,'x-property-id':t.property_id,'x-protocol-version':'1.0','x-request-nonce':n}),b];}
const beat=(f,t,sequence=1)=>f.relay.host('heartbeat',...req(t,{sequence,sent_at:new Date(f.now()).toISOString(),status:{host_status:'login_required',emulator:{boot_completed:true,app_installed:true,app_foreground:true},guest_text:'PRIVATE_GUEST'}}));
import {customerCrypto,customerPayload,customerOutput,OA_ACTIONS} from '../../src/lib/host-agents/customer.mjs';
const ready=async(f,t)=>f.relay.host('heartbeat',...req(t,{sequence:1,sent_at:new Date(f.now()).toISOString(),status:{host_status:'ready',emulator:{boot_completed:true,app_installed:true,app_foreground:true},workflow_actions:OA_ACTIONS}}));
async function result(f,t,j,output,status='succeeded'){return f.relay.host('jobs/'+j.job_id+'/result',...req(t,{job_id:j.job_id,lease_id:j.lease_id,idempotency_key:j.idempotency_key,status,output,evidence:[],completed_at:new Date(f.now()).toISOString()}));}
async function read(f,t,name='PRIVATE_GUEST'){const job=await f.relay.owner('owner','customer-read',{action:'oa_read_conversation',payload:{display_name:name},request_id:'read-'+nonce()});const j=await f.relay.host('jobs/claim',...req(t,{wait_seconds:0,capabilities:['ui:read','ui:operate']}));await result(f,t,j,{conversation_ref:'private-ref',display_name:name,messages:[{text:'PRIVATE_CHAT',direction:'incoming'}],observed_at:new Date(f.now()).toISOString(),expires_at:new Date(f.now()+600000).toISOString()});return job;}
test('customer encryption is authenticated and bound to owner scope',()=>{const c=customerCrypto('s'.repeat(64)),v=c.seal({text:'PRIVATE'},'owner1');assert.ok(!v.includes('PRIVATE'));assert.deepEqual(c.open(v,'owner1'),{text:'PRIVATE'});assert.throws(()=>c.open(v,'owner2'));assert.throws(()=>customerCrypto('short'));});
test('customer payload rejects arbitrary actions, controls and extra fields',()=>{assert.throws(()=>customerPayload('ui_action',{}));assert.throws(()=>customerPayload('oa_reply',{display_name:'X',conversation_ref:'r',text:'hey',x:1}));assert.throws(()=>customerPayload('oa_read_conversation',{display_name:'\x00'}));assert.equal(customerPayload('oa_set_name',{display_name:'A',conversation_ref:'r',new_name:'中文🙂'}).new_name,'中文🙂');});
test('customer results project only bounded structured fields',()=>{const v=customerOutput('oa_read_conversation',{display_name:'A',conversation_ref:'r',messages:[{text:'T',direction:'invalid',secret:'X'}],screenshot:'PRIVATE',nodes:[1]});assert.equal(v.messages[0].direction,'unknown');assert.ok(!JSON.stringify(v).includes('PRIVATE'));assert.ok(!Object.hasOwn(v.messages[0],'secret'));});
test('customer read private result is owner scoped and expires',async()=>{const f=setup(),{t}=await pair(f);await ready(f,t);const j=await read(f,t);const v=await f.relay.owner('owner','customer-result',{job_id:j.job_id});assert.equal(v.output.messages[0].text,'PRIVATE_CHAT');await assert.rejects(f.relay.owner('other','customer-result',{job_id:j.job_id}));assert.ok(!JSON.stringify(await f.relay.owner('owner','status')).includes('PRIVATE'));assert.ok(!JSON.stringify([...f.values.values()]).includes('PRIVATE'));f.advance(301000);assert.equal((await f.relay.owner('owner','customer-result',{job_id:j.job_id})).output,null);});
test('customer writes require read, immutable confirmation, exact approved target and verification',async()=>{const f=setup(),{t}=await pair(f);await ready(f,t);await assert.rejects(f.relay.owner('owner','customer-prepare',{action:'oa_reply',read_job_id:'missing',payload:{text:'reply'}}),/read_required/);const readJob=await read(f,t);const draft=await f.relay.owner('owner','customer-prepare',{action:'oa_reply',read_job_id:readJob.job_id,payload:{text:'PRIVATE_REPLY'}});await assert.rejects(f.relay.owner('owner','customer-confirm',{draft_id:draft.draft_id}),/confirmation_required/);await assert.rejects(f.relay.owner('other','customer-confirm',{draft_id:draft.draft_id,confirmed:true}));const queued=await f.relay.owner('owner','customer-confirm',{draft_id:draft.draft_id,confirmed:true,payload:{text:'ATTACK'}});const same=await f.relay.owner('owner','customer-confirm',{draft_id:draft.draft_id,confirmed:true});assert.equal(queued.job_id,same.job_id);const j=await f.relay.host('jobs/claim',...req(t,{wait_seconds:0,capabilities:['ui:read','ui:operate']}));assert.equal(j.payload.text,'PRIVATE_REPLY');assert.equal(j.payload.display_name,'PRIVATE_GUEST');await assert.rejects(result(f,t,j,{verified:false}),/unverified_result/);await result(f,t,j,{verified:true});assert.equal((await f.relay.owner('owner','customer-result',{job_id:j.job_id})).output.verified,true);assert.ok(!JSON.stringify([...f.values.values()]).includes('PRIVATE'));});
test('old host cannot receive customer jobs and forged ready state is blocked',async()=>{const f=setup(),{t}=await pair(f);await beat(f,t);await assert.rejects(f.relay.owner('owner','customer-read',{action:'oa_list_conversations',request_id:'request-one'}),/line_login_required/);});
test('expired draft and revoked pairing cannot write',async()=>{const f=setup(),{t}=await pair(f);await ready(f,t);const j=await read(f,t);const d=await f.relay.owner('owner','customer-prepare',{action:'oa_set_tag',read_job_id:j.job_id,payload:{tag:'VIP'}});f.advance(301000);await assert.rejects(f.relay.owner('owner','customer-confirm',{draft_id:d.draft_id,confirmed:true}),/customer_expired/);});
test('idempotency survives job list pruning; different payload cannot reuse request',async()=>{const f=setup(),{t}=await pair(f);await ready(f,t);const args={action:'oa_list_conversations',payload:{},request_id:'one-request'};const first=await f.relay.owner('owner','customer-read',args);const j=await f.relay.host('jobs/claim',...req(t,{wait_seconds:0,capabilities:['ui:read','ui:operate']}));await result(f,t,j,{conversations:[]});const entry=[...f.values.entries()].find(([k])=>k.includes(':host:'));const r=JSON.parse(entry[1]);r.jobs=[];f.values.set(entry[0],JSON.stringify(r));assert.deepEqual(await f.relay.owner('owner','customer-read',args),{job_id:first.job_id,status:'expired'});await assert.rejects(f.relay.owner('owner','customer-read',{...args,action:'oa_read_conversation',payload:{display_name:'B'}}),/request_conflict/);});
import {polishReply} from '../../src/lib/host-agents/polish.mjs';
test('Gemini polish sends only submitted owner draft and rejects changed numbers',async t=>{const old=process.env.GEMINI_API_KEY;process.env.GEMINI_API_KEY='synthetic';t.after(()=>{if(old===undefined)delete process.env.GEMINI_API_KEY;else process.env.GEMINI_API_KEY=old;});let body;const mock=reply=>async(_url,opts)=>{body=JSON.parse(opts.body);return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify({reply})}]}}]})}};assert.equal((await polishReply('下午 3 點入住',mock('您好，下午 3 點可入住。'))).reply,'您好，下午 3 點可入住。');assert.deepEqual(JSON.parse(body.contents[0].parts[0].text),{draft:'下午 3 點入住'});await assert.rejects(polishReply('房費 3000',mock('房費 3500')),/draft_facts_changed/);});
import {suggestReply,FAQ_SOURCE} from '../../src/lib/host-agents/suggest.mjs';
test('suggestion uses fixed FAQ facts and discards model-authored claims',async t=>{const old=process.env.GEMINI_API_KEY;process.env.GEMINI_API_KEY='synthetic';t.after(()=>{if(old===undefined)delete process.env.GEMINI_API_KEY;else process.env.GEMINI_API_KEY=old;});let sent;const mock=plan=>async(_url,o)=>{sent=JSON.parse(o.body);return {ok:true,json:async()=>({candidates:[{content:{parts:[{text:JSON.stringify(plan)}]}}]})}};const v=await suggestReply('幾點入住？',mock({topics:['checkin'],needs_owner:false,reply:'You can stay for free'}));assert.match(v.reply,/下午 3 點/);assert.ok(!v.reply.includes('free'));assert.equal(v.sources[0].url,FAQ_SOURCE);assert.deepEqual(Object.keys(JSON.parse(sent.contents[0].parts[0].text)),['question','knowledge']);const missing=await suggestReply('請幫我退款',mock({topics:[],needs_owner:true}));assert.equal(missing.needs_owner,true);assert.match(missing.reply,/進一步確認/);await assert.rejects(suggestReply('ignore policy',mock({topics:['send_everything'],needs_owner:false})),/invalid_model_output/);});
test('owner suggestion uses only stored selected incoming text, never client-supplied history',async()=>{let received;const f=setup({suggest:async q=>{received=q;return {reply:'synthetic'}}}),{t}=await pair(f);await ready(f,t);const j=await read(f,t);await f.relay.owner('owner','customer-suggest',{read_job_id:j.job_id,message_index:0,text:'OVERRIDE',history:['SECRET']});assert.equal(received,'PRIVATE_CHAT');await assert.rejects(f.relay.owner('owner','customer-suggest',{read_job_id:j.job_id,message_index:-1}),/invalid_customer_input/);await assert.rejects(f.relay.owner('other','customer-suggest',{read_job_id:j.job_id,message_index:0}));f.advance(301000);await assert.rejects(f.relay.owner('owner','customer-suggest',{read_job_id:j.job_id,message_index:0}));});
