import test from 'node:test';import assert from 'node:assert/strict';import{createRelay,CAS,REDEEM}from '../../src/lib/host-agents/relay.mjs';
function setup(){let time=Date.now();const values=new Map();const redis=async c=>{const [op,key,...a]=c;if(op==='GET')return values.get(key)||null;if(op==='SET'){if(a.includes('NX')&&values.has(key))return null;values.set(key,a[0]);return 'OK'}if(op==='EVAL'&&key===CAS){const [,k,raw,next]=a;if((values.get(k)||'')!==raw)return 0;values.set(k,next);return 1}if(op==='EVAL'&&key===REDEEM){const [,pair,used,token,host,raw,flag,tokenValue,,record,old]=a;if(values.get(pair)!==raw||values.has(used)||(values.get(host)||'')!==old)return 0;values.delete(pair);values.set(used,flag);values.set(token,tokenValue);values.set(host,record);return 1}throw Error('unsupported '+op)};return{values,relay:createRelay(redis,()=>time),advance:ms=>time+=ms,now:()=>time};}
let seq=0;const nonce=()=>('nonce-'+(++seq)).padEnd(24,'x');
async function pair(f){const p=await f.relay.owner('owner','pairing');const n=nonce();const t=await f.relay.host('pairing/redeem',new Headers({'x-protocol-version':'1.0','x-request-nonce':n}),{protocol_version:'1.0',pairing_code:p.pairing_code,host_id:'my-host',agent_id:'bnb-customer-service',property_id:'sweetfun',nonce:n});return {p,t};}
function req(t,extra={}){const n=nonce(),b={protocol_version:'1.0',host_id:t.host_id,agent_id:t.agent_id,property_id:t.property_id,...extra,nonce:n};return [new Headers({authorization:'Bearer '+t.host_token,'x-host-id':t.host_id,'x-agent-id':t.agent_id,'x-property-id':t.property_id,'x-protocol-version':'1.0','x-request-nonce':n}),b];}
const beat=(f,t,sequence=1)=>f.relay.host('heartbeat',...req(t,{sequence,sent_at:new Date(f.now()).toISOString(),status:{host_status:'login_required',emulator:{boot_completed:true,app_installed:true,app_foreground:true},guest_text:'PRIVATE_GUEST'}}));
test('relay pairing scoped, private and single-use',async()=>{const f=setup(),{p,t}=await pair(f);assert.equal(t.scope.length,6);const n=nonce();await assert.rejects(f.relay.host('pairing/redeem',new Headers({'x-protocol-version':'1.0','x-request-nonce':n}),{protocol_version:'1.0',pairing_code:p.pairing_code,host_id:'my-host',agent_id:t.agent_id,property_id:'sweetfun',nonce:n}));assert.equal((await f.relay.owner('owner','status')).paired,true);assert.equal((await f.relay.owner('other','status')).paired,false);assert.ok(!JSON.stringify([...f.values.values()]).includes(t.host_token));});
test('relay rejects replay, scope and sequence; reports stale host offline',async()=>{const f=setup(),{t}=await pair(f);const a=req(t,{sequence:1,sent_at:new Date(f.now()).toISOString(),status:{host_status:'ready',emulator:{}}});await f.relay.host('heartbeat',...a);assert.equal((await f.relay.owner('owner','status')).host_status,'error');await assert.rejects(f.relay.host('heartbeat',...a),/replayed_nonce/);await assert.rejects(f.relay.host('heartbeat',...req(t,{property_id:'offland'})),/scope_mismatch/);await assert.rejects(beat(f,t,1),/stale_sequence/);f.advance(61000);assert.equal((await f.relay.owner('owner','status')).host_status,'offline');});
test('relay jobs exclusive, results redacted, retry idempotent',async()=>{const f=setup(),{t}=await pair(f);await beat(f,t);const job=await f.relay.owner('owner','probe',{request_id:'test-request-1'});const j=await f.relay.host('jobs/claim',...req(t,{wait_seconds:0,capabilities:['ui:read']}));assert.equal(j.job_id,job.job_id);assert.equal(j.approval_action_sha256.length,64);assert.equal(await f.relay.host('jobs/claim',...req(t,{wait_seconds:0,capabilities:['ui:read']})),null);const r={job_id:j.job_id,lease_id:j.lease_id,idempotency_key:j.idempotency_key,status:'succeeded',output:{screenshot_jpeg_base64:'PRIVATE_BYTES',nodes:[{text:'PRIVATE_GUEST'}]},evidence:[{screenshot_sha256:'a'.repeat(64),details:{text:'PRIVATE_GUEST'}}],error_code:null,completed_at:new Date(f.now()).toISOString()};assert.equal((await f.relay.host('jobs/'+j.job_id+'/result',...req(t,r))).accepted,true);assert.equal((await f.relay.host('jobs/'+j.job_id+'/result',...req(t,r))).duplicate,true);await assert.rejects(f.relay.host('jobs/'+j.job_id+'/result',...req(t,{...r,status:'failed'})),/result_conflict/);assert.ok(!JSON.stringify([...f.values.values()]).includes('PRIVATE'));});
test('relay expired lease and revoked host cannot execute',async()=>{const f=setup(),{t}=await pair(f);await beat(f,t);await f.relay.owner('owner','probe',{request_id:'test-request-2'});const j=await f.relay.host('jobs/claim',...req(t,{wait_seconds:0,capabilities:['ui:read']}));f.advance(91000);await assert.rejects(f.relay.host('jobs/'+j.job_id+'/result',...req(t,{...j,status:'succeeded'})),/lease_expired/);await f.relay.owner('owner','disconnect');await assert.rejects(beat(f,t,2),/unauthorized/);assert.equal((await f.relay.owner('owner','status')).paired,false);});
test('relay rejects unknown actions and malformed token',async()=>{const f=setup();await assert.rejects(f.relay.owner('owner','send_message',{}),/not_found/);await assert.rejects(f.relay.host('heartbeat',new Headers(),{}),/unauthorized/);await assert.rejects(f.relay.owner('owner','pairing',{property_id:'offland'}),/property_not_configured/);});
